## In this notebook I will
1. Pull data from the [Deportation Data Project]("https://deportationdata.org/data/ice.html") 
2. Extract ICE Arrests for 2022, 2023, 2024, 2025, 2026 
3. Clean the data for each year.

In [1]:
## import necessary libraries
import pandas as pd

### EXTRACTION1: Pulling 2022 data

In [2]:
## let's pull data that i have downloaded. starting with the first file
df1 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/RawData/2026-ICLI-00005_Arrests_FY23_20260311_Redacted.xlsx')
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 - 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Administrative Arrests FY2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172938,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172939,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
172940,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172941,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,NaN
172942,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [3]:
#### As you can see: we don't need the first couple rows, it has unneeded rows. Let's remove the rows
df1 = df1.iloc[5:]
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
6,2022-10-05 11:08:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002880c7d1c7fc09144a3fe22a5b45c5c204a6
7,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
8,2023-01-12 09:53:00,NaN,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2023-01-13 00:00:00,2019-07-25 00:00:00,"BKI GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Bakersfield, CA IHP Sub Office",1 Convicted Criminal,1,00005ee8ff539795f2114c218f445634884d01e4
9,2023-08-22 16:07:00,NaN,NaN,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-09-05 00:00:00,2023-08-23 00:00:00,CLARK COUNTY DETENTION CENTER,NaN,"LAS VEGAS, NV, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0000ee96b6cebdde068bf9d73f4473288c652188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172938,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172939,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
172940,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172941,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,NaN
172942,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [4]:
## the first row is actually the header we want. Let's drop the header and put the actual header we want there
## create a new df, just to be safe
df1.columns = df1.iloc[0]
df1_titled = df1[1:].reset_index(drop=True)
df1_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2022-10-05 11:08:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002880c7d1c7fc09144a3fe22a5b45c5c204a6
1,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
2,2023-01-12 09:53:00,NaN,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2023-01-13 00:00:00,2019-07-25 00:00:00,"BKI GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Bakersfield, CA IHP Sub Office",1 Convicted Criminal,1,00005ee8ff539795f2114c218f445634884d01e4
3,2023-08-22 16:07:00,NaN,NaN,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-09-05 00:00:00,2023-08-23 00:00:00,CLARK COUNTY DETENTION CENTER,NaN,"LAS VEGAS, NV, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0000ee96b6cebdde068bf9d73f4473288c652188
4,2022-11-18 11:40:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,HAITI,Male,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00012138344f907502a4c08061b6793d9694f390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172932,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172933,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
172934,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172935,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,NaN
172936,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [5]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df1_titled['Apprehension Date'] = pd.to_datetime(df1_titled['Apprehension Date'])

In [13]:
## create a subset of data for only 2022
##first: pull anything before 2023
df_2022 = df1_titled[df1_titled['Apprehension Date'] < '2023-01-01']

In [14]:
##now: pull anything after 2021 from the same subset. 
df_2022 = df_2022[df_2022['Apprehension Date'] > '2021-12-31']

In [16]:
##This is your 2022 ICE arrests data
df_2022

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2022-10-05 11:08:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002880c7d1c7fc09144a3fe22a5b45c5c204a6
4,2022-11-18 11:40:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,HAITI,Male,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00012138344f907502a4c08061b6793d9694f390
6,2022-10-20 07:51:00,NaN,INDIANA,NaN,Chicago Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,MEXICO,Male,NaN,NaN,"INP GENERAL AREA, NON-SPECIFIC",-,"ERO - Indianapolis, IN Sub-Office",3 Other Immigration Violator,NaN,0001881592ace06cdaa5af0f8bf065385a6e3491
7,2022-12-14 08:50:00,NaN,NaN,NaN,Denver Area of Responsibility,Mobile Criminal Alien Team,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,NaN,DENVER COUNTY,NaN,"DENVER, CO, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00019fa9e0aa94625220c91d01d1285f5accf081
9,2022-11-03 11:21:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00037689c6eb841eef84ffa417b8669c914acf78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171367,2022-12-30 10:24:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2022-12-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,NaN
171369,2022-12-30 12:14:54,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,NaN,NaN,"COLUMBUS, NM, POE",NaN,NaN,NaN
171370,2022-12-31 08:29:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2022-12-31 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
171371,2022-12-31 09:04:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2022-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,NaN
171830,2022-12-14 11:00:00,NaN,NaN,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,Located,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"CHI GENERAL AREA, NON-SPECIFIC",NaN,"CHICAGO, IL, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [17]:
##Let us do Extraction 1: 2022 ICE Arrests data
df_2022.to_csv('FilteredData/2022ICEArrestsData.csv', index=False)

## Extraction2: Pulling 2023 data

In [30]:
##let's check to see if there are any 2023 data lurking in the first file
## create a subset of data for only 2023 in file 1 
df_2023pt1 = df1_titled[df1_titled['Apprehension Date'] > '2022-12-31']
df_2023pt1

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
1,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
2,2023-01-12 09:53:00,NaN,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2023-01-13 00:00:00,2019-07-25 00:00:00,"BKI GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Bakersfield, CA IHP Sub Office",1 Convicted Criminal,1,00005ee8ff539795f2114c218f445634884d01e4
3,2023-08-22 16:07:00,NaN,NaN,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-09-05 00:00:00,2023-08-23 00:00:00,CLARK COUNTY DETENTION CENTER,NaN,"LAS VEGAS, NV, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0000ee96b6cebdde068bf9d73f4473288c652188
5,2023-02-22 10:03:00,NaN,FLORIDA,NaN,Miami Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,NaN,Miramar ICE/ERO Sub-Office,-,"MIAMI, FL, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00012b367a6ea8f65031c1247b30605404cfad04
8,2023-06-15 10:46:00,NaN,CALIFORNIA,NaN,Los Angeles Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,A-Proceedings Terminated,...,RUSSIA,Female,NaN,NaN,"SAA GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Santa Ana, CA Sub-Office",3 Other Immigration Violator,NaN,0002b915db9660d07d5d18c713b35f46a3f11996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172932,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172933,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
172934,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172935,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,NaN
172936,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [40]:
##let's check to see if there are any 2023 data lurking in the first file
## create a subset of data for only 2023 in file 1 and double check it is only 2023 data
df_2023pt1 = df_2023pt1[df_2023pt1['Apprehension Date'] < '2024-01-01']
df_2023pt1

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
1,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
2,2023-01-12 09:53:00,NaN,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2023-01-13 00:00:00,2019-07-25 00:00:00,"BKI GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Bakersfield, CA IHP Sub Office",1 Convicted Criminal,1,00005ee8ff539795f2114c218f445634884d01e4
3,2023-08-22 16:07:00,NaN,NaN,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-09-05 00:00:00,2023-08-23 00:00:00,CLARK COUNTY DETENTION CENTER,NaN,"LAS VEGAS, NV, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0000ee96b6cebdde068bf9d73f4473288c652188
5,2023-02-22 10:03:00,NaN,FLORIDA,NaN,Miami Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,NaN,Miramar ICE/ERO Sub-Office,-,"MIAMI, FL, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00012b367a6ea8f65031c1247b30605404cfad04
8,2023-06-15 10:46:00,NaN,CALIFORNIA,NaN,Los Angeles Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,A-Proceedings Terminated,...,RUSSIA,Female,NaN,NaN,"SAA GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Santa Ana, CA Sub-Office",3 Other Immigration Violator,NaN,0002b915db9660d07d5d18c713b35f46a3f11996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172932,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172933,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
172934,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172935,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,NaN
172936,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [41]:
##There was 2023 data in the first file as well, let's extract it
df_2023pt1.to_csv('FilteredData/2023ICEArrestsDataPT.1.csv', index=False)

In [33]:
##Ok, to be safe, let's check the file 2 in the zip folder for stray 2022 arrests and then start looking for 2023 data as well
df2 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/RawData/2026-ICLI-00005_Arrests_FY24_20260311_Redacted.xlsx')
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 - 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Administrative Arrests FY2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113839,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
113840,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
113841,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
113842,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
113843,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [34]:
#### As you can see: we don't need the first couple rows, it has unneeded rows. Let's remove the rows
df2 = df2.iloc[5:]
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
6,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
7,2024-06-13 08:06:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Deported/Removed,...,HONDURAS,Male,2024-06-26 00:00:00,2023-12-07 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,1,000058df2daf065f42816437ebf455e2d0d38558
8,2024-02-02 09:54:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,PERU,Male,2025-07-05 00:00:00,2025-05-23 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,0000aec67e823c9306515cc63f285a76fc3b6591
9,2024-03-14 09:49:00,NaN,WASHINGTON,NaN,Seattle Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-03-26 00:00:00,2023-06-30 00:00:00,FEDERAL DETENTION CENTER (FDC),Criminal Alien Program Surge Enforcement Team ...,"SEATTLE, WA, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,0000c5cf8abc2d9f6b8aa424933343957c7801bb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113839,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
113840,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
113841,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
113842,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
113843,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [35]:
## the first row is actually the header we want. Let's drop the header and put the actual header we want there
## create a new df, just to be safe
df2.columns = df2.iloc[0]
df2_titled = df2[1:].reset_index(drop=True)
df2_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
1,2024-06-13 08:06:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Deported/Removed,...,HONDURAS,Male,2024-06-26 00:00:00,2023-12-07 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,1,000058df2daf065f42816437ebf455e2d0d38558
2,2024-02-02 09:54:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,PERU,Male,2025-07-05 00:00:00,2025-05-23 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,0000aec67e823c9306515cc63f285a76fc3b6591
3,2024-03-14 09:49:00,NaN,WASHINGTON,NaN,Seattle Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-03-26 00:00:00,2023-06-30 00:00:00,FEDERAL DETENTION CENTER (FDC),Criminal Alien Program Surge Enforcement Team ...,"SEATTLE, WA, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,0000c5cf8abc2d9f6b8aa424933343957c7801bb
4,2024-08-06 12:17:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Female,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000c68c7cf317c4fd47056ac433e9a0d994a1e4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113833,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
113834,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
113835,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
113836,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
113837,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [36]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df2_titled['Apprehension Date'] = pd.to_datetime(df2_titled['Apprehension Date'])
df2_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
1,2024-06-13 08:06:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Deported/Removed,...,HONDURAS,Male,2024-06-26 00:00:00,2023-12-07 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,1,000058df2daf065f42816437ebf455e2d0d38558
2,2024-02-02 09:54:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,PERU,Male,2025-07-05 00:00:00,2025-05-23 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,0000aec67e823c9306515cc63f285a76fc3b6591
3,2024-03-14 09:49:00,NaN,WASHINGTON,NaN,Seattle Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-03-26 00:00:00,2023-06-30 00:00:00,FEDERAL DETENTION CENTER (FDC),Criminal Alien Program Surge Enforcement Team ...,"SEATTLE, WA, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,0000c5cf8abc2d9f6b8aa424933343957c7801bb
4,2024-08-06 12:17:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Female,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000c68c7cf317c4fd47056ac433e9a0d994a1e4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113833,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
113834,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
113835,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
113836,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
113837,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [38]:
## create a subset of data for only 2022
##first: pull anything before 2023
df_2022pt2 = df2_titled[df2_titled['Apprehension Date'] < '2023-01-01']
df_2022pt2

Empty DataFrame
Columns: [Apprehension Date, Apprehension Type, State, County, TOA Current Duty AOR, Apprehension Final Program, Arresting Agency, Apprehension Method, Apprehension Criminality, Case Status, Case Category, Departure Country, Final Order Yes No, Birth Date, Birth Year, Citizenship Country, Gender, Departed Date, Final Order Date, Apprehension Site Landmark, Operation, TOA Current Duty Site, Case Criminality, Case Threat Level, Anonymized Identifier]
Index: []

[0 rows x 25 columns]

## Extraction for 2022 complete!

In [43]:
## let's pull 2023 data from file 2
df_2023pt2 = df2_titled[df2_titled['Apprehension Date'] < '2024-01-01']
df_2023pt2

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
8,2023-11-03 11:37:00,NaN,NaN,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-12-20 00:00:00,2016-04-09 00:00:00,STUART,NaN,"ERO - Stuart, FL Sub Office",1 Convicted Criminal,3,00038f76045b3d1bb8b62d85365e29a9924a58f1
9,2023-11-01 07:54:00,NaN,CALIFORNIA,NaN,Los Angeles Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-11-01 00:00:00,2017-07-02 00:00:00,VENTURA FUGITIVE OPERATIONS,-,"ERO - Ventura, CA Sub Office",1 Convicted Criminal,2,0003a23f3f22d9a40e269cf7401c551a29a88c24
16,2023-11-24 11:12:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,ACTIVE,...,COLOMBIA,Male,NaN,2024-06-20 00:00:00,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0006989f31392d9aa50a51d46c451395b0547050
19,2023-11-01 11:42:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,2024-10-10 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,000732077b82caf319021e0154c64f9a77a6118e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112744,2023-12-29 07:02:06,NaN,NaN,NaN,NaN,Law Enforcement Area Response Units,ICE,Inspections,3 Other Immigration Violator,NaN,...,ALGERIA,Male,NaN,NaN,NaN,NaN,"DERBY LINE, VT (I-91), POE",NaN,NaN,NaN
112745,2023-12-29 12:34:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-12-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,2,NaN
112746,2023-12-29 12:13:49,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,MEXICO,Female,NaN,NaN,NaN,NaN,"DOUGLAS, AZ, POE",NaN,NaN,NaN
112747,2023-12-30 09:07:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
112748,2023-12-31 09:52:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [44]:
## let's pull 2023 data from file 2
df_2023pt2 = df_2023pt2[df_2023pt2['Apprehension Date'] > '2022-12-31']
df_2023pt2

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
8,2023-11-03 11:37:00,NaN,NaN,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-12-20 00:00:00,2016-04-09 00:00:00,STUART,NaN,"ERO - Stuart, FL Sub Office",1 Convicted Criminal,3,00038f76045b3d1bb8b62d85365e29a9924a58f1
9,2023-11-01 07:54:00,NaN,CALIFORNIA,NaN,Los Angeles Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-11-01 00:00:00,2017-07-02 00:00:00,VENTURA FUGITIVE OPERATIONS,-,"ERO - Ventura, CA Sub Office",1 Convicted Criminal,2,0003a23f3f22d9a40e269cf7401c551a29a88c24
16,2023-11-24 11:12:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,ACTIVE,...,COLOMBIA,Male,NaN,2024-06-20 00:00:00,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0006989f31392d9aa50a51d46c451395b0547050
19,2023-11-01 11:42:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,2024-10-10 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,000732077b82caf319021e0154c64f9a77a6118e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112744,2023-12-29 07:02:06,NaN,NaN,NaN,NaN,Law Enforcement Area Response Units,ICE,Inspections,3 Other Immigration Violator,NaN,...,ALGERIA,Male,NaN,NaN,NaN,NaN,"DERBY LINE, VT (I-91), POE",NaN,NaN,NaN
112745,2023-12-29 12:34:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-12-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,2,NaN
112746,2023-12-29 12:13:49,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,MEXICO,Female,NaN,NaN,NaN,NaN,"DOUGLAS, AZ, POE",NaN,NaN,NaN
112747,2023-12-30 09:07:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
112748,2023-12-31 09:52:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [45]:
##Let's put down pt.2 
df_2023pt2.to_csv('FilteredData/2023ICEArrestsDataPT.2.csv', index=False)

## 2023 ICE Arrests pulled