## In this notebook
1. Pull and combine all 2023 arrests data
2. Analyze it for:

    a. arrests in year by state for 2023
    
    b. arrests in NY for 2023
    
    c. arrests in Capital Region for 2023

In [2]:
## import necessary libraries
import pandas as pd

In [3]:
df1 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/FilteredData/2023ICEArrestsDataPT.1.csv')
df1

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
1,2023-01-12 09:53:00,NaN,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2023-01-13 00:00:00,2019-07-25 00:00:00,"BKI GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Bakersfield, CA IHP Sub Office",1 Convicted Criminal,1.0,00005ee8ff539795f2114c218f445634884d01e4
2,2023-08-22 16:07:00,NaN,NaN,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-09-05 00:00:00,2023-08-23 00:00:00,CLARK COUNTY DETENTION CENTER,NaN,"LAS VEGAS, NV, DOCKET CONTROL OFFICE",1 Convicted Criminal,3.0,0000ee96b6cebdde068bf9d73f4473288c652188
3,2023-02-22 10:03:00,NaN,FLORIDA,NaN,Miami Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,NaN,Miramar ICE/ERO Sub-Office,-,"MIAMI, FL, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00012b367a6ea8f65031c1247b30605404cfad04
4,2023-06-15 10:46:00,NaN,CALIFORNIA,NaN,Los Angeles Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,A-Proceedings Terminated,...,RUSSIA,Female,NaN,NaN,"SAA GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Santa Ana, CA Sub-Office",3 Other Immigration Violator,NaN,0002b915db9660d07d5d18c713b35f46a3f11996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124372,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
124373,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
124374,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
124375,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1.0,NaN
124376,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [4]:
df2 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/FilteredData/2023ICEArrestsDataPT.2.csv')
df2

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
1,2023-11-03 11:37:00,NaN,NaN,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-12-20 00:00:00,2016-04-09 00:00:00,STUART,NaN,"ERO - Stuart, FL Sub Office",1 Convicted Criminal,3.0,00038f76045b3d1bb8b62d85365e29a9924a58f1
2,2023-11-01 07:54:00,NaN,CALIFORNIA,NaN,Los Angeles Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-11-01 00:00:00,2017-07-02 00:00:00,VENTURA FUGITIVE OPERATIONS,-,"ERO - Ventura, CA Sub Office",1 Convicted Criminal,2.0,0003a23f3f22d9a40e269cf7401c551a29a88c24
3,2023-11-24 11:12:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,ACTIVE,...,COLOMBIA,Male,NaN,2024-06-20 00:00:00,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3.0,0006989f31392d9aa50a51d46c451395b0547050
4,2023-11-01 11:42:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,2024-10-10 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,000732077b82caf319021e0154c64f9a77a6118e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29113,2023-12-29 07:02:06,NaN,NaN,NaN,NaN,Law Enforcement Area Response Units,ICE,Inspections,3 Other Immigration Violator,NaN,...,ALGERIA,Male,NaN,NaN,NaN,NaN,"DERBY LINE, VT (I-91), POE",NaN,NaN,NaN
29114,2023-12-29 12:34:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-12-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,2.0,NaN
29115,2023-12-29 12:13:49,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,MEXICO,Female,NaN,NaN,NaN,NaN,"DOUGLAS, AZ, POE",NaN,NaN,NaN
29116,2023-12-30 09:07:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
29117,2023-12-31 09:52:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [6]:
df23 = pd.concat([df1, df2])
df23

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
1,2023-01-12 09:53:00,NaN,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2023-01-13 00:00:00,2019-07-25 00:00:00,"BKI GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Bakersfield, CA IHP Sub Office",1 Convicted Criminal,1.0,00005ee8ff539795f2114c218f445634884d01e4
2,2023-08-22 16:07:00,NaN,NaN,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-09-05 00:00:00,2023-08-23 00:00:00,CLARK COUNTY DETENTION CENTER,NaN,"LAS VEGAS, NV, DOCKET CONTROL OFFICE",1 Convicted Criminal,3.0,0000ee96b6cebdde068bf9d73f4473288c652188
3,2023-02-22 10:03:00,NaN,FLORIDA,NaN,Miami Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,NaN,Miramar ICE/ERO Sub-Office,-,"MIAMI, FL, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00012b367a6ea8f65031c1247b30605404cfad04
4,2023-06-15 10:46:00,NaN,CALIFORNIA,NaN,Los Angeles Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,A-Proceedings Terminated,...,RUSSIA,Female,NaN,NaN,"SAA GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Santa Ana, CA Sub-Office",3 Other Immigration Violator,NaN,0002b915db9660d07d5d18c713b35f46a3f11996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29113,2023-12-29 07:02:06,NaN,NaN,NaN,NaN,Law Enforcement Area Response Units,ICE,Inspections,3 Other Immigration Violator,NaN,...,ALGERIA,Male,NaN,NaN,NaN,NaN,"DERBY LINE, VT (I-91), POE",NaN,NaN,NaN
29114,2023-12-29 12:34:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-12-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,2.0,NaN
29115,2023-12-29 12:13:49,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,MEXICO,Female,NaN,NaN,NaN,NaN,"DOUGLAS, AZ, POE",NaN,NaN,NaN
29116,2023-12-30 09:07:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
29117,2023-12-31 09:52:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [7]:
df23_state = df23["State"].value_counts()
df23_state

TEXAS                             27849
NEW YORK                          10176
CALIFORNIA                         8121
FLORIDA                            7215
NEW JERSEY                         7131
MASSACHUSETTS                      3885
LOUISIANA                          2568
ILLINOIS                           2551
COLORADO                           2547
TENNESSEE                          2431
ARIZONA                            2139
WASHINGTON                         2134
GEORGIA                            2123
VIRGINIA                           1807
OKLAHOMA                           1803
NORTH CAROLINA                     1688
PENNSYLVANIA                       1590
MARYLAND                           1523
MISSISSIPPI                        1487
WISCONSIN                          1463
OHIO                               1445
ARKANSAS                           1255
SOUTH CAROLINA                     1245
ALABAMA                            1217
INDIANA                            1210
MICHIGAN                           1153
MINNESOTA                          1041
KENTUCKY                           1016
UTAH                               1004
NEBRASKA                            999
MISSOURI                            768
KANSAS                              697
NEVADA                              596
IOWA                                542
MAINE                               455
RHODE ISLAND                        429
PUERTO RICO                         328
WEST VIRGINIA                       302
NEW HAMPSHIRE                       258
DELAWARE                            204
OREGON                              185
CONNECTICUT                         169
IDAHO                               161
WYOMING                             158
NEW MEXICO                          119
MONTANA                              65
NORTH DAKOTA                         59
SOUTH DAKOTA                         56
HAWAII                               56
ALASKA                               54
VERMONT                              40
DISTRICT OF COLUMBIA                 36
NORTHERN MARIANA ISLANDS             18
VIRGIN ISLANDS                       18
GUAM                                 10
ARMED FORCES - THE AMERICAS           5
ARMED SERVICES - PACIFIC              1
FEDERATED STATES OF MICRONESIA        1
Name: State, dtype: int64

In [8]:
df23_state.to_csv('RawData/2023DeportationByState.csv', index=True)

In [9]:
df_NY = df23.query('State == "NEW YORK"') 
df_NY

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
44,2023-06-13 10:03:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,PERU,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00176b0473662c102ba2ff0a9e38e0f6a8b67288
46,2023-08-10 09:33:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,PERU,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00181d0c5dc266fcb8f5a35933db9c60a58846ac
70,2023-03-13 10:23:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0027b2f36139a990bb874e47e8d0364a5081a172
77,2023-05-03 11:10:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,002d5cf385472101bf4837938382aec2725ce523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28626,2023-12-06 14:40:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Located,2 Pending Criminal Charges,ACTIVE,...,GUATEMALA,Female,NaN,NaN,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",2 Pending Criminal Charges,NaN,fef1dc81fb1588f3d0479f8e2541176acb31939e
28670,2023-11-06 09:18:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ff5483b058ec55352b49429eebd16ff40c0f8a32
28681,2023-11-09 10:20:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,1 Convicted Criminal,ACTIVE,...,VENEZUELA,Male,NaN,2024-02-14 00:00:00,CAP - NASSAU COUNTY JAIL NY STATE,NaN,"ERO - Central Islip, NY Sub Office",1 Convicted Criminal,3.0,ff6ed8bd53247d7a72f585abc77536fe8530d775
28729,2023-12-22 07:17:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,EL SALVADOR,Male,2024-02-02 00:00:00,2024-01-12 00:00:00,WENDE CORRECTIONAL FACILITY,NaN,"ERO - Batavia, NY SPC Sub-Office",1 Convicted Criminal,1.0,ffd87d104e73203563c43797d090d34f78d663fe
28751,2023-12-13 12:42:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,2025-04-30 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ffffa86834be2a43223dc2e774417527b9962d69

In [10]:
NYcounts = df_NY['Apprehension Site Landmark'].value_counts()
NYcounts

NDD - 26 FEDERAL PLAZA NY, NY                     7619
ERIE COUNTY                                        538
CIP GENERAL AREA, NON-SPECIFIC                     511
SARATOGA COUNTY                                    367
WENDE CORRECTIONAL FACILITY                        299
                                                  ...
CAP - NEW ROCHELLE POLICE DEPARTMENT NY STATE        1
CAP - OSSINING TOWN POLICE DEPARTMENT NY STATE       1
COLUMBIA COUNTY                                      1
CAP - WHITE PLAINS CITY POLICE NY STATE              1
ONTARIO COUNTY JAIL                                  1
Name: Apprehension Site Landmark, Length: 98, dtype: int64

In [11]:
NYcounts.to_csv('FilteredData/2023DeportationByNY.csv', index=True)

In [12]:
df_NY['Apprehension Site Landmark'].unique()

array(['NDD - 26 FEDERAL PLAZA NY, NY', 'WENDE CORRECTIONAL FACILITY',
       'ERIE COUNTY', 'CIP GENERAL AREA, NON-SPECIFIC', 'SARATOGA COUNTY',
       'NBG GENERAL AREA, NON-SPECIFIC', 'ONONDAGA COUNTY',
       'CAP - SUFFOLK COUNTY JAIL NY STATE', 'ERIE COUNTY JAIL',
       'FEDERAL CORRECTIONAL INSTITUTE RAY BROOK',
       'CAP - BOP BROOKLYN NY STATE', 'JCART STREET ARREST NY STATE',
       'CLINTON COUNTY', 'MONROE COUNTY',
       'HAR GENERAL AREA, NON-SPECIFIC', 'FUGITIVE OPERATIONS NY STATE',
       'CAP - OTISVILLE FEDERAL CORRECTIONAL FACILITY NY STATE',
       'ATD NY STATE', 'CAP - PUTNAM COUNTY JAIL NY STATE',
       'CAP - USM - EASTERN DISTRICT NY State', 'ICE ERO NEWARK',
       'CAP - QUEENS CENTRAL BOOKING NY State',
       'CAP - ORANGE COUNTY JAIL NY STATE',
       'CAP - NASSAU COUNTY JAIL NY STATE', 'NON-DETAINED AND JUVENILE',
       'DELAWARE COUNTY JAIL', 'TOMPKINS COUNTY', 'GENESEE COUNTY',
       'NON-DETAINED and Juvenile', 'ONEIDA COUNTY',
       'CAP - ULSTER CORRECTIONAL FACILITY NY STATE',
       'SCHENECTADY COUNTY JAIL', 'ALBANY COUNTY JAIL', 'WYOMING COUNTY',
       'At large arrest Suffolk County', 'RENSSELAER COUNTY JAIL',
       'FUGITIVE OPERATIONS NY State', 'GREENE COUNTY JAIL',
       'NYC GENERAL AREA, NON-SPECIFIC',
       'CAP - USM - SOUTHERN DISTRICT NY STATE',
       'CAP - CITY OF POUGHKEEPSIE POLICE DEPARTMENT NY STATE',
       'FTM-SW FL Regional Juvenile Detention Center', 'ORLEANS COUNTY',
       'CAP - NEWBURGH CITYPOLICE DEPARTMENT, NY STATE',
       'CAP - PUTNAM COUNTY SHERRIFFS DEPARTMENT, NY STATE', 'NEWARK PD',
       'DO NOT USE', 'RENSSELAER COUNTY',
       'CAP - YONKERS CITY POLICE DEPARTMENT NY STATE', 'ALBANY COUNTY',
       'BOP BROOKLYN', 'At large arrest Nassau County',
       'NEW GENERAL AREA, NON-SPECIFIC',
       'CAP - VCBC - VERNON C. BAIN CENTER NY STATE',
       'ALBION CORRECTIONAL FACILITY',
       'CAP - MIDDLETOWN CITY POLICE DEPARTMENT, NY STATE',
       'CAP - NEWBURGH TOWN POLICE DEPARTMENT, NY STATE',
       'BROOME COUNTY JAIL', 'ESSEX COUNTY JAIL', 'CHENANGO COUNTY',
       'BROOME COUNTY',
       'ALBUQUERQUE INTERNATIONAL AIRPORT, ALBUQUERQUE, NM',
       'CAP - NEW ROCHELLE POLICE DEPARTMENT NY STATE', nan,
       'ONONDAGA COUNTY JAIL', 'NEWARK CITY',
       'BUFFALO GENERAL - Do Not Use',
       'CAP - OSSINING TOWN POLICE DEPARTMENT NY STATE',
       'COLUMBIA COUNTY', 'COLUMBIA COUNTY JAIL',
       'CAP - WHITE PLAINS CITY POLICE NY STATE',
       'CAP - OSSINING VILLAGE POLICE DEPARTMENT NY STATE',
       'CAP - BEDFORD CORRECTIONAL FACILITY NY STATE',
       'CAP - MAMARONECK VILLAGE POLICE DEPARTMENT NY STATE',
       'CAP - SAUGERTIES POLICE DEPARTMENT NY STATE',
       'MONROE COUNTY JAIL', 'WASHINGTON COUNTY', 'WAYNE COUNTY',
       'HERKIMER COUNTY JAIL', 'YATES COUNTY JAIL', 'ONTARIO COUNTY',
       'SCHENECTADY COUNTY', 'CAP - NEW YORK STATE POLICE NY STATE',
       'FRANKLIN COUNTY JAIL', 'DANBURY, CT', 'ONEIDA COUNTY JAIL',
       'CAP - QUEENSBORO CORRECTIONAL FACILITY NY STATE', 'SENECA COUNTY',
       'CAP - SPRING VALLEY POLICE DEPARTMENT, NY STATE',
       'SNS GENERAL AREA, NON-SPECIFIC',
       'CAP - ROCKLAND COUNTY SHERRIFFS DEPARTMENT, NY STATE',
       'XLI GENERAL AREA, NON-SPECIFIC', 'XAY GENERAL AREA, NON-SPECIFIC',
       'CAP - UNITED STATES PROBATION SDNY NY STATE',
       'CAP - WESTCHESTER COUNTY JAIL NY STATE', 'CAYUGA COUNTY JAIL',
       'STUBEN COUNTY JAIL',
       'CAP - WESTCHESTER COUNTY POLICE DEPARTMENT, NY STATE',
       'ONTARIO COUNTY JAIL'], dtype=object)

In [13]:
CapitalRegion= ['ALBANY COUNTY','RENSSELAER COUNTY', 'SARATOGA COUNTY', 'GREENE COUNTY', 'WARREN COUNTY', 'WARREN COUNTY JAIL', 'SCHENECTADY COUNTY JAIL', 'SARATOGA COUNTY JAIL', 'RENSSELAER COUNTY JAIL', 'WASHINGTON CORRECTIONAL FACILITY', 'WASHINGTON COUNTY JAIL']

In [15]:
df_CR = df_NY[df_NY['Apprehension Site Landmark'].isin(CapitalRegion)]
df_CR

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
366,2023-05-30 09:03:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,2024-04-18 00:00:00,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,00cf2e092b073e67da4c5ab3082b9cdb72958bee
440,2023-01-26 14:02:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,A-Proceedings Terminated,...,GUYANA,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,00f545b0177c9c3357481bfadac32b7dee3a07b7
540,2023-01-18 13:25:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,2025-05-15 00:00:00,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,012dc1cd6fe32c554f0b971626bc513cb04642b1
764,2023-03-09 11:48:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,2025-04-23 00:00:00,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,01a74016eef6603f3883756956415895ef7600b0
1152,2023-08-09 08:52:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,0287c819a3507f7740dbe4faedb666a546a18f0e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25930,2023-10-17 11:14:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,A-Proceedings Terminated,...,CUBA,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,e704df8ee3885e80aa5b89fcee4b6ee986b99590
26841,2023-11-07 10:03:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-07 00:00:00,2025-11-24 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,3.0,eeda15e05a188d30d1944ad69bf8563d87ed81c4
27226,2023-10-19 09:26:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,AFGHANISTAN,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f248ffd74ed764022224a56c6ab42674044f9403
28152,2023-12-14 11:17:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Located,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,NICARAGUA,Male,2024-03-07 00:00:00,2023-12-12 00:00:00,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,3.0,faeb8ccfa2106eaaf202f24c375753ff96a45b0d
28589,2023-10-19 14:13:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VIETNAM,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fe8a2a1517a37e14c71ee6f84d70c57553e99e07

In [16]:
df_CR["Apprehension Site Landmark"].value_counts()

SARATOGA COUNTY            367
ALBANY COUNTY               12
SCHENECTADY COUNTY JAIL      3
RENSSELAER COUNTY JAIL       3
RENSSELAER COUNTY            3
Name: Apprehension Site Landmark, dtype: int64

In [17]:
df_CR.to_csv('FilteredData/2023CapitalRegionICEArrests.csv', index = True)