## In this notebook
1. Pull and combine all 2024 arrests data
2. Analyze it for:

    a. arrests in year by state for 2024
    
    b. arrests in NY for 2024
    
    c. arrests in Capital Region for 2024

In [1]:
## import necessary libraries
import pandas as pd

In [2]:
df1 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/FilteredData/2024ICEArrestsDataPT.1.csv')
df1

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2024-06-13 08:06:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Deported/Removed,...,HONDURAS,Male,2024-06-26 00:00:00,2023-12-07 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,1.0,000058df2daf065f42816437ebf455e2d0d38558
1,2024-02-02 09:54:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,PERU,Male,2025-07-05 00:00:00,2025-05-23 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,0000aec67e823c9306515cc63f285a76fc3b6591
2,2024-03-14 09:49:00,NaN,WASHINGTON,NaN,Seattle Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-03-26 00:00:00,2023-06-30 00:00:00,FEDERAL DETENTION CENTER (FDC),Criminal Alien Program Surge Enforcement Team ...,"SEATTLE, WA, DOCKET CONTROL OFFICE",1 Convicted Criminal,1.0,0000c5cf8abc2d9f6b8aa424933343957c7801bb
3,2024-08-06 12:17:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Female,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000c68c7cf317c4fd47056ac433e9a0d994a1e4
4,2024-02-12 12:58:00,NaN,TEXAS,NaN,Houston Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"SHELBY COUNTY PROBATION, CENTER, TX",-,"HOUSTON, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,2.0,00018ed5cd20d7343e228cfdc007aa996a2aff9f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84760,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
84761,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
84762,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
84763,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
84764,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [3]:
df2 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/FilteredData/2024ICEArrestsDataPT.2.csv')
df2

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2024-06-13 08:06:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Deported/Removed,...,HONDURAS,Male,2024-06-26 00:00:00,2023-12-07 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,1.0,000058df2daf065f42816437ebf455e2d0d38558
1,2024-02-02 09:54:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,PERU,Male,2025-07-05 00:00:00,2025-05-23 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,0000aec67e823c9306515cc63f285a76fc3b6591
2,2024-03-14 09:49:00,NaN,WASHINGTON,NaN,Seattle Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-03-26 00:00:00,2023-06-30 00:00:00,FEDERAL DETENTION CENTER (FDC),Criminal Alien Program Surge Enforcement Team ...,"SEATTLE, WA, DOCKET CONTROL OFFICE",1 Convicted Criminal,1.0,0000c5cf8abc2d9f6b8aa424933343957c7801bb
3,2024-08-06 12:17:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Female,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000c68c7cf317c4fd47056ac433e9a0d994a1e4
4,2024-02-12 12:58:00,NaN,TEXAS,NaN,Houston Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"SHELBY COUNTY PROBATION, CENTER, TX",-,"HOUSTON, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,2.0,00018ed5cd20d7343e228cfdc007aa996a2aff9f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84760,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
84761,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
84762,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
84763,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
84764,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [4]:
df24 = pd.concat([df1, df2])
df24

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2024-06-13 08:06:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Deported/Removed,...,HONDURAS,Male,2024-06-26 00:00:00,2023-12-07 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,1.0,000058df2daf065f42816437ebf455e2d0d38558
1,2024-02-02 09:54:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,PERU,Male,2025-07-05 00:00:00,2025-05-23 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,0000aec67e823c9306515cc63f285a76fc3b6591
2,2024-03-14 09:49:00,NaN,WASHINGTON,NaN,Seattle Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-03-26 00:00:00,2023-06-30 00:00:00,FEDERAL DETENTION CENTER (FDC),Criminal Alien Program Surge Enforcement Team ...,"SEATTLE, WA, DOCKET CONTROL OFFICE",1 Convicted Criminal,1.0,0000c5cf8abc2d9f6b8aa424933343957c7801bb
3,2024-08-06 12:17:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Female,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000c68c7cf317c4fd47056ac433e9a0d994a1e4
4,2024-02-12 12:58:00,NaN,TEXAS,NaN,Houston Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"SHELBY COUNTY PROBATION, CENTER, TX",-,"HOUSTON, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,2.0,00018ed5cd20d7343e228cfdc007aa996a2aff9f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84760,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
84761,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
84762,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
84763,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
84764,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [5]:
df24_state = df24["State"].value_counts()
df24_state

TEXAS                             33562
FLORIDA                           11072
CALIFORNIA                         8548
NEW YORK                           6586
NEW JERSEY                         4398
TENNESSEE                          3706
LOUISIANA                          3460
GEORGIA                            3348
KENTUCKY                           2984
ARIZONA                            2878
INDIANA                            2680
NORTH CAROLINA                     2360
ILLINOIS                           2344
ALABAMA                            2334
VIRGINIA                           2316
OKLAHOMA                           2254
MISSISSIPPI                        2096
MARYLAND                           2032
MASSACHUSETTS                      2016
PENNSYLVANIA                       2008
SOUTH CAROLINA                     1924
MISSOURI                           1784
ARKANSAS                           1732
WASHINGTON                         1674
UTAH                               1646
MICHIGAN                           1470
MINNESOTA                          1412
COLORADO                           1376
OHIO                               1302
WISCONSIN                          1272
NEVADA                             1042
KANSAS                              982
NEBRASKA                            546
PUERTO RICO                         486
IOWA                                446
CONNECTICUT                         396
RHODE ISLAND                        352
DELAWARE                            330
WEST VIRGINIA                       296
MAINE                               280
WYOMING                             232
NEW MEXICO                          220
OREGON                              186
NORTH DAKOTA                        148
VIRGIN ISLANDS                      140
IDAHO                               120
NEW HAMPSHIRE                        92
HAWAII                               92
SOUTH DAKOTA                         60
ALASKA                               38
GUAM                                 34
VERMONT                              30
MONTANA                              28
NORTHERN MARIANA ISLANDS             26
DISTRICT OF COLUMBIA                 20
ARMED FORCES - THE AMERICAS          18
FEDERATED STATES OF MICRONESIA       14
ARMED SERVICES - PACIFIC              2
Name: State, dtype: int64

In [6]:
df24_state.to_csv('FilteredData/2024DeportationByState.csv', index=True)

In [7]:
df_NY = df24.query('State == "NEW YORK"') 
df_NY

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
26,2024-09-25 10:11:04,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000e00362a7ce05a098386f88e81e146cef564b8
31,2024-01-18 12:49:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00119da62775f775fc6b28dbb06716f7306d6060
34,2024-04-16 10:38:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00143e74440995cd4e3e78c3db761ed59cd82db5
62,2024-04-22 11:17:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0026771284ae9e758f97c7b8b95ad0032990f3bb
76,2024-04-19 09:49:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,002fc00e4fd8fab678b361e9c8f7397d8f2856d8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83630,2024-03-22 08:04:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,ACTIVE,...,JAMAICA,Male,NaN,2012-06-22 00:00:00,WENDE CORRECTIONAL FACILITY,NaN,BATAVIA CMD CTR NY DCO,1 Convicted Criminal,1.0,ffeb4fd4dff55ed3b996bd1e935f7a443be1fe22
83647,2024-01-30 11:36:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,HONDURAS,Male,2025-11-17 00:00:00,2025-07-08 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,fff8f3ae1841b2023ed0a646483fb585dcc7360a
83651,2024-02-29 07:37:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,EL SALVADOR,Male,2024-03-22 00:00:00,2023-12-19 00:00:00,WENDE CORRECTIONAL FACILITY,NaN,"ERO - Batavia, NY SPC Sub-Office",1 Convicted Criminal,1.0,fffa9541d55830bab785c5a5b78cacf6fda28cfe
83654,2024-05-15 09:55:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,UZBEKISTAN,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,fffc1c12e37bccf2693b5deb67a7f40b3744b156
83658,2024-04-23 11:00:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",SBI,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,fffd8cddaedf2db4e037b8421d8bf22ae75a15fd

In [8]:
NYcounts = df_NY['Apprehension Site Landmark'].value_counts()
NYcounts

NDD - 26 FEDERAL PLAZA NY, NY     4358
WENDE CORRECTIONAL FACILITY        546
CIP GENERAL AREA, NON-SPECIFIC     380
FUGITIVE OPERATIONS NY STATE       182
SARATOGA COUNTY                    172
                                  ...
CHAUTAUQUA COUNTY JAIL               2
WAYNE COUNTY                         2
SCHUYLER COUNTY                      2
WHP GENERAL AREA, NON-SPECIFIC       2
ESSEX COUNTY                         2
Name: Apprehension Site Landmark, Length: 77, dtype: int64

In [9]:
NYcounts.to_csv('FilteredData/2024DeportationByNY.csv', index=True)

In [10]:
df_NY['Apprehension Site Landmark'].unique()

array(['NDD - 26 FEDERAL PLAZA NY, NY', 'WENDE CORRECTIONAL FACILITY',
       'SARATOGA COUNTY', 'FUGITIVE OPERATIONS NY STATE',
       'CIP GENERAL AREA, NON-SPECIFIC', 'NBG GENERAL AREA, NON-SPECIFIC',
       'FEDERAL CORRECTIONAL INSTITUTE RAY BROOK',
       'CAP - NASSAU COUNTY JAIL NY STATE',
       'CAP - PUTNAM COUNTY JAIL NY STATE', 'ONONDAGA COUNTY',
       'JCART STREET ARREST NY STATE',
       'CAP - ORANGE COUNTY JAIL NY STATE',
       'CAP - MANHATTAN CRIMINAL COURT NY STATE',
       'CAP - BOP BROOKLYN NY STATE', 'NON-DETAINED AND JUVENILE',
       'GENESEE COUNTY', 'CAP - ULSTER CORRECTIONAL FACILITY NY STATE',
       'NON-DETAINED and Juvenile', 'At large arrest Nassau County',
       'LIVINGSTON COUNTY', 'SCHENECTADY COUNTY JAIL', 'ERIE COUNTY',
       'BOP BROOKLYN', 'SCHENECTADY COUNTY',
       'CAP - QUEENS CENTRAL BOOKING NY State', 'CLINTON COUNTY',
       'BROOME COUNTY JAIL', 'WASHINGTON COUNTY JAIL', 'ATD NY STATE',
       'At large arrest Suffolk County', 'FOS GENERAL AREA, NON-SPECIFIC',
       'ERIE COUNTY JAIL',
       'CAP - EASTCHESTER TOWN POLICE DEPARTMENT NY STATE',
       'ICE ERO NEWARK', 'MONTGOMERY COUNTY JAIL',
       'NEW GENERAL AREA, NON-SPECIFIC', 'ALBANY COUNTY JAIL',
       'BROOME COUNTY', 'ALBANY COUNTY',
       'CAP - US FEDERAL PROBATION NY STATE', 'RENSSELAER COUNTY JAIL',
       'SARATOGA COUNTY JAIL', 'NIAGARA COUNTY', 'MONROE COUNTY',
       'FUGITIVE OPERATIONS NY State',
       'CAP - BEDFORD CORRECTIONAL FACILITY NY STATE',
       'ELMIRA CORRECTIONAL FACILITY',
       'CAP - COUNTY, STATE, LEA REF NY STATE',
       'CAP - OTISVILLE FEDERAL CORRECTIONAL FACILITY NY STATE',
       'CHAUTAUQUA COUNTY JAIL',
       'CAP - ULSTER COUNTY SHERRIFFS DEPARTMENT NY STATE',
       'ONTARIO COUNTY', 'WAYNE COUNTY', 'SCHUYLER COUNTY',
       'CLINTON COUNTY JAIL', 'WHP GENERAL AREA, NON-SPECIFIC',
       'NEWARK PD', 'ONONDAGA COUNTY JAIL', 'ICE ERO MOUNT LAUREL',
       'GREENE COUNTY', 'ORLEANS COUNTY JAIL',
       'ALBION CORRECTIONAL FACILITY', 'STUART', 'HERKIMER COUNTY',
       'STUBEN COUNTY JAIL', 'CHILDRENS VILLAGE', 'ONTARIO COUNTY JAIL',
       'CAP - USM - SOUTHERN DISTRICT NY STATE', 'DELAWARE COUNTY JAIL',
       'LEW GENERAL AREA, NON-SPECIFIC', nan,
       'VCAS - QUEENS CENTRAL BOOKING, NY STATE', 'YATES COUNTY JAIL',
       'CAP At-large Nassau County', 'MADISON COUNTY JAIL',
       'JCART STREET ARREST',
       'CAP - UNITED STATES PROBATION SDNY NY STATE', 'ESSEX COUNTY'],
      dtype=object)

In [11]:
CapitalRegion= ['ALBANY COUNTY','RENSSELAER COUNTY', 'SARATOGA COUNTY', 'GREENE COUNTY', 'WARREN COUNTY', 'WARREN COUNTY JAIL', 'SCHENECTADY COUNTY JAIL', 'SARATOGA COUNTY JAIL', 'RENSSELAER COUNTY JAIL', 'WASHINGTON CORRECTIONAL FACILITY', 'WASHINGTON COUNTY JAIL']

In [12]:
df_CR = df_NY[df_NY['Apprehension Site Landmark'].isin(CapitalRegion)]
df_CR

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
171,2024-09-16 11:17:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,TURKIYE,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,006eb45cf15f4dbd0f7ebb85c2741360221a9b5e
1343,2024-03-18 10:41:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,GUATEMALA,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,042cd1b70275cc4990becf997445a92ba5b04c76
3753,2024-07-01 10:11:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Located,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Male,NaN,2024-03-20 00:00:00,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,0b891dd5ac090b27c96df3fcb849612a489b7792
4635,2024-05-31 11:09:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,ACTIVE,...,GUYANA,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,0e1c5cc4d721d94ae184b7f18b9791fbead54c93
5394,2024-01-08 12:04:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,MEXICO,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,1083d402bb309261ba7b2d6b0c39ddf307c70781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81200,2024-02-27 12:01:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Located,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f888c2a45ac167ba15399fea59af69178a330a2a
81585,2024-08-30 12:46:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f99be4c1fb3dfe52bd6904d6597532a0ba3f922a
82353,2024-04-03 10:29:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,AFGHANISTAN,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fbf3a0d47ab7ef7707d3b98a455ee77ad347b3e7
82482,2024-05-08 09:52:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,A-Proceedings Terminated,...,GUATEMALA,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fc4db7b8b1cd850d8e3f6afc432e8ebf1b0ca7fc
83353,2024-03-12 11:15:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Located,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,ff0e08c7bbf75414fcc89e7b292569028cb91fb0

In [13]:
df_CR["Apprehension Site Landmark"].value_counts()

SARATOGA COUNTY            172
ALBANY COUNTY               16
SCHENECTADY COUNTY JAIL      4
RENSSELAER COUNTY JAIL       4
SARATOGA COUNTY JAIL         4
GREENE COUNTY                4
WASHINGTON COUNTY JAIL       2
Name: Apprehension Site Landmark, dtype: int64

In [15]:
df_CR.to_csv('FilteredData/2024CapitalRegionICEArrests.csv', index = True)