### CONTEXT: 
So, I have the data from Sandra Fish on Colorado removals. Now, the code itself looks like it already starts with clean data for a specific year. But it uses data from Arrests, Detainers, Detentions, Encounters, AND removals. 

Now pulling that for each year for each category is a lot. So for the sake of time and exploration, i am first going to pull just 2025 data in this sheet so i can start analyzingand see if my analysis is correct. 

### In this notebook I will:
1. Pull data from the Deportation Data Project
2. Extract ICE Detainers for 2025

In [1]:
## import necessary libraries
import pandas as pd

### Extraction 1: 2025 detention data

In [2]:
df1 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/TEST2/RawData/Detentions/2026-ICLI-00005_Detentions_FY24_20260311_Redacted.xlsx')
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICE Detentions FY2023 - FY2026YTD (10/01/2022 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572086,2024-09-27 07:30:00,2024-09-27 07:30:00,MCALLEN HOLD ROOM,2024-09-27 09:45:00,2024-09-27 17:13:00,Transferred,2024-09-27 00:00:00,Voluntary Return,NaN,Male,...,2024-09-18 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572087,2024-09-27 07:30:00,2024-09-27 11:30:00,HARLINGEN HOLD ROOM,2024-09-27 17:13:00,2024-09-27 17:13:00,Voluntary Return,2024-09-27 00:00:00,Voluntary Return,NaN,Male,...,2024-09-18 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572088,2024-09-27 13:12:00,2024-09-27 13:12:00,HARLINGEN HOLD ROOM,2024-09-27 13:14:00,2024-09-27 13:14:00,Voluntary Return,2024-09-27 00:00:00,Voluntary Return,NaN,Male,...,2022-05-09 00:00:00,ERO Criminal Alien Program,2024-09-16 00:00:00,2024-09-26 00:00:00,Convicted,C,Misdemeanor,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572089,2024-09-28 08:00:00,2024-09-28 08:00:00,MCALLEN HOLD ROOM,2024-09-28 09:58:00,2024-09-28 09:58:00,Voluntary Return,2024-09-28 00:00:00,Voluntary Return,NaN,Male,...,2024-09-10 00:00:00,ERO Criminal Alien Program,2024-09-10 00:00:00,2024-09-26 00:00:00,Convicted,C,Misdemeanor,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572090,2024-09-30 10:15:00,2024-09-30 10:15:00,HARLINGEN HOLD ROOM,2024-09-30 15:30:00,2024-09-30 15:30:00,Voluntary Return,2024-09-30 00:00:00,Voluntary Return,NaN,Male,...,2015-01-27 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN

In [3]:
#### As you can see: we don't need the first couple rows, it has unneeded rows. Let's remove the rows
df1 = df1.iloc[5:]
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
6,2024-06-13 08:49:00,2024-06-13 08:49:00,VAL VERDE DETENTION CENTER,2024-06-13 17:46:00,2024-06-26 03:45:00,Transferred,2024-06-26 00:00:00,Removed,NaN,Male,...,2023-12-05 00:00:00,ERO Criminal Alien Program,2009-03-07 00:00:00,2009-03-26 00:00:00,Convicted,C,NaN,"ERO - Del Rio, TX Sub Office",San Antonio Area of Responsibility,000058df2daf065f42816437ebf455e2d0d38558
7,2024-06-13 08:49:00,2024-06-13 20:45:00,SOUTH TEXAS ICE PROCESSING CENTER,2024-06-26 03:45:00,2024-06-26 03:45:00,Removed,2024-06-26 00:00:00,Removed,NaN,Male,...,2023-12-05 00:00:00,ERO Criminal Alien Program,2009-03-07 00:00:00,2009-03-26 00:00:00,Convicted,C,NaN,"ERO - South Texas, TX Detention Facility",San Antonio Area of Responsibility,000058df2daf065f42816437ebf455e2d0d38558
8,2023-09-29 10:59:00,2024-03-26 10:11:00,JACKSON PARISH CORRECTIONAL CENTER,2024-06-13 10:55:00,2024-06-13 10:55:00,Removed,2024-06-13 00:00:00,Removed,NaN,Male,...,2023-09-24 00:00:00,Border Patrol,NaN,NaN,NaN,NaN,NaN,"ERO - Winnfield, LA Sub-Office",New Orleans Area of Responsibility,0000a95e4792ab35c9771a2b86884550dde32dd8
9,2024-03-14 10:30:00,2024-03-14 10:30:00,SEATTLE FIELD OFFICE HOLD ROOM,2024-03-14 15:27:00,2024-03-26 17:43:00,Transferred,2024-03-26 00:00:00,Removed,NaN,Male,...,NaN,ERO Criminal Alien Program,2022-01-27 00:00:00,2022-11-02 00:00:00,Convicted,C,Felony,"SEATTLE, WA, DOCKET CONTROL OFFICE",Seattle Area of Responsibility,0000c5cf8abc2d9f6b8aa424933343957c7801bb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572086,2024-09-27 07:30:00,2024-09-27 07:30:00,MCALLEN HOLD ROOM,2024-09-27 09:45:00,2024-09-27 17:13:00,Transferred,2024-09-27 00:00:00,Voluntary Return,NaN,Male,...,2024-09-18 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572087,2024-09-27 07:30:00,2024-09-27 11:30:00,HARLINGEN HOLD ROOM,2024-09-27 17:13:00,2024-09-27 17:13:00,Voluntary Return,2024-09-27 00:00:00,Voluntary Return,NaN,Male,...,2024-09-18 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572088,2024-09-27 13:12:00,2024-09-27 13:12:00,HARLINGEN HOLD ROOM,2024-09-27 13:14:00,2024-09-27 13:14:00,Voluntary Return,2024-09-27 00:00:00,Voluntary Return,NaN,Male,...,2022-05-09 00:00:00,ERO Criminal Alien Program,2024-09-16 00:00:00,2024-09-26 00:00:00,Convicted,C,Misdemeanor,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572089,2024-09-28 08:00:00,2024-09-28 08:00:00,MCALLEN HOLD ROOM,2024-09-28 09:58:00,2024-09-28 09:58:00,Voluntary Return,2024-09-28 00:00:00,Voluntary Return,NaN,Male,...,2024-09-10 00:00:00,ERO Criminal Alien Program,2024-09-10 00:00:00,2024-09-26 00:00:00,Convicted,C,Misdemeanor,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572090,2024-09-30 10:15:00,2024-09-30 10:15:00,HARLINGEN HOLD ROOM,2024-09-30 15:30:00,2024-09-30 15:30:00,Voluntary Return,2024-09-30 00:00:00,Voluntary Return,NaN,Male,...,2015-01-27 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN

In [4]:
## the first row is actually the header we want. Let's drop the header and put the actual header we want there
## create a new df, just to be safe
df1.columns = df1.iloc[0]
df1_titled = df1[1:].reset_index(drop=True)
df1_titled

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
0,2024-06-13 08:49:00,2024-06-13 08:49:00,VAL VERDE DETENTION CENTER,2024-06-13 17:46:00,2024-06-26 03:45:00,Transferred,2024-06-26 00:00:00,Removed,NaN,Male,...,2023-12-05 00:00:00,ERO Criminal Alien Program,2009-03-07 00:00:00,2009-03-26 00:00:00,Convicted,C,NaN,"ERO - Del Rio, TX Sub Office",San Antonio Area of Responsibility,000058df2daf065f42816437ebf455e2d0d38558
1,2024-06-13 08:49:00,2024-06-13 20:45:00,SOUTH TEXAS ICE PROCESSING CENTER,2024-06-26 03:45:00,2024-06-26 03:45:00,Removed,2024-06-26 00:00:00,Removed,NaN,Male,...,2023-12-05 00:00:00,ERO Criminal Alien Program,2009-03-07 00:00:00,2009-03-26 00:00:00,Convicted,C,NaN,"ERO - South Texas, TX Detention Facility",San Antonio Area of Responsibility,000058df2daf065f42816437ebf455e2d0d38558
2,2023-09-29 10:59:00,2024-03-26 10:11:00,JACKSON PARISH CORRECTIONAL CENTER,2024-06-13 10:55:00,2024-06-13 10:55:00,Removed,2024-06-13 00:00:00,Removed,NaN,Male,...,2023-09-24 00:00:00,Border Patrol,NaN,NaN,NaN,NaN,NaN,"ERO - Winnfield, LA Sub-Office",New Orleans Area of Responsibility,0000a95e4792ab35c9771a2b86884550dde32dd8
3,2024-03-14 10:30:00,2024-03-14 10:30:00,SEATTLE FIELD OFFICE HOLD ROOM,2024-03-14 15:27:00,2024-03-26 17:43:00,Transferred,2024-03-26 00:00:00,Removed,NaN,Male,...,NaN,ERO Criminal Alien Program,2022-01-27 00:00:00,2022-11-02 00:00:00,Convicted,C,Felony,"SEATTLE, WA, DOCKET CONTROL OFFICE",Seattle Area of Responsibility,0000c5cf8abc2d9f6b8aa424933343957c7801bb
4,2024-03-14 10:30:00,2024-03-14 15:45:00,NW ICE PROCESSING CTR,2024-03-26 11:27:00,2024-03-26 17:43:00,Transferred,2024-03-26 00:00:00,Removed,NaN,Male,...,NaN,ERO Criminal Alien Program,2022-01-27 00:00:00,2022-11-02 00:00:00,Convicted,C,Felony,"SEATTLE, WA, DOCKET CONTROL OFFICE",Seattle Area of Responsibility,0000c5cf8abc2d9f6b8aa424933343957c7801bb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572080,2024-09-27 07:30:00,2024-09-27 07:30:00,MCALLEN HOLD ROOM,2024-09-27 09:45:00,2024-09-27 17:13:00,Transferred,2024-09-27 00:00:00,Voluntary Return,NaN,Male,...,2024-09-18 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572081,2024-09-27 07:30:00,2024-09-27 11:30:00,HARLINGEN HOLD ROOM,2024-09-27 17:13:00,2024-09-27 17:13:00,Voluntary Return,2024-09-27 00:00:00,Voluntary Return,NaN,Male,...,2024-09-18 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572082,2024-09-27 13:12:00,2024-09-27 13:12:00,HARLINGEN HOLD ROOM,2024-09-27 13:14:00,2024-09-27 13:14:00,Voluntary Return,2024-09-27 00:00:00,Voluntary Return,NaN,Male,...,2022-05-09 00:00:00,ERO Criminal Alien Program,2024-09-16 00:00:00,2024-09-26 00:00:00,Convicted,C,Misdemeanor,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572083,2024-09-28 08:00:00,2024-09-28 08:00:00,MCALLEN HOLD ROOM,2024-09-28 09:58:00,2024-09-28 09:58:00,Voluntary Return,2024-09-28 00:00:00,Voluntary Return,NaN,Male,...,2024-09-10 00:00:00,ERO Criminal Alien Program,2024-09-10 00:00:00,2024-09-26 00:00:00,Convicted,C,Misdemeanor,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN
572084,2024-09-30 10:15:00,2024-09-30 10:15:00,HARLINGEN HOLD ROOM,2024-09-30 15:30:00,2024-09-30 15:30:00,Voluntary Return,2024-09-30 00:00:00,Voluntary Return,NaN,Male,...,2015-01-27 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",Harlingen Area of Responsibility,NaN

In [5]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df1_titled['Stay Book In Date Time'] = pd.to_datetime(df1_titled['Stay Book In Date Time'])

In [6]:
## create a subset of data for only 2022
##first: pull anything before 2023
df_2025pt1 = df1_titled[df1_titled['Stay Book In Date Time'] < '2026-01-01']

In [7]:
##now: pull anything after 2021 from the same subset. 
df_2025pt1 = df_2025pt1[df_2025pt1['Stay Book In Date Time'] > '2024-12-31']

In [8]:
##This is your 2025 ICE detainers data
df_2025pt1

Empty DataFrame
Columns: [Stay Book In Date Time, Book In Date Time, Detention Facility, Book Out Date Time, Stay Book Out Date Time, Detention Release Reason, Stay Book Out Date, Stay Release Reason, Religion, Gender, Marital Status, Ethnicity, Birth Country, Citizenship Country, Entry Status, Known Terrorist Yes No, Suspected Gang Yes No, MSC Charge, MSC Sentence Days, MSC Sentence Months, MSC Sentence Years, MSC Charge Code, Aggravated Felon Yes No, Offense INA 236C Yes No, Case INA 236C Yes No, Bond Posted Date, Bond Posted Amount, Case Status, Case Category, Final Order Yes No, Final Order Date, Case Threat Level, Detainee Classification, Final Charge, Departed Date, Departure Country, Initial Bond Set Amount, Initial Bond Set Date, Detention Facility Code, Birth Date, Birth Year, Book In Criminality, Race, Entry Date, Apprehension Final Program, MSC Charge Date, MSC Conviction Date, MSC Criminal Charge Status, MSC Criminal Charge Status Code, MSC Crime Class, Book In Site, Book In AOR, Anonymized Identifier]
Index: []

[0 rows x 53 columns]

### No 2025 data in file 1.

In [9]:
##Ok, to be safe, let's check the file 2 in the zip folder for stray 2022 arrests and then start looking for 2023 data as well
df2 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/TEST2/RawData/Detentions/2026-ICLI-00005_Detentions_FY25_20260311_Redacted.xlsx')
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICE Detentions FY2023 - FY2026YTD (10/01/2022 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890985,2025-09-30 16:52:00,2025-09-30 16:52:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:52:00,2025-09-30 16:52:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890986,2025-09-30 16:56:00,2025-09-30 16:56:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:57:00,2025-09-30 16:57:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890987,2025-09-30 16:58:00,2025-09-30 16:58:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:58:00,2025-09-30 16:58:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890988,2025-09-30 16:59:00,2025-09-30 16:59:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:59:00,2025-09-30 16:59:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890989,2025-08-06 15:30:00,2025-08-06 15:30:00,MONTGOMERY PROCESSING CTR,2025-08-24 09:08:00,2025-08-24 09:08:00,Removed,2025-08-24 00:00:00,Removed,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Montgomery County, TX Sub Office",Houston Area of Responsibility,NaN

In [10]:
#### As you can see: we don't need the first couple rows, it has unneeded rows. Let's remove the rows
df2 = df2.iloc[5:]
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
6,2024-12-27 01:16:00,2024-12-27 01:16:00,FLORENCE STAGING FACILITY,2024-12-27 08:48:00,2024-12-27 08:48:00,Removed,2024-12-27 00:00:00,Removed,NaN,Male,...,2024-11-13 00:00:00,Border Patrol,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,00001bc128707c1bc0f44bfd6fcc3fa9c3d4f195
7,2025-09-17 10:00:00,2025-09-17 10:00:00,DALLAS F.O. HOLD,2025-09-18 19:02:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE",Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
8,2025-09-17 10:00:00,2025-09-18 22:43:00,BLUEBONNET DET FCLTY,2025-09-26 09:28:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Bluebonnet Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
9,2025-09-17 10:00:00,2025-09-26 17:25:00,PRAIRIELAND DETENTION CENTER,2025-09-27 12:03:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Prairieland Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890985,2025-09-30 16:52:00,2025-09-30 16:52:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:52:00,2025-09-30 16:52:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890986,2025-09-30 16:56:00,2025-09-30 16:56:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:57:00,2025-09-30 16:57:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890987,2025-09-30 16:58:00,2025-09-30 16:58:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:58:00,2025-09-30 16:58:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890988,2025-09-30 16:59:00,2025-09-30 16:59:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:59:00,2025-09-30 16:59:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890989,2025-08-06 15:30:00,2025-08-06 15:30:00,MONTGOMERY PROCESSING CTR,2025-08-24 09:08:00,2025-08-24 09:08:00,Removed,2025-08-24 00:00:00,Removed,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Montgomery County, TX Sub Office",Houston Area of Responsibility,NaN

In [11]:
## the first row is actually the header we want. Let's drop the header and put the actual header we want there
## create a new df, just to be safe
df2.columns = df2.iloc[0]
df2_titled = df2[1:].reset_index(drop=True)
df2_titled

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
0,2024-12-27 01:16:00,2024-12-27 01:16:00,FLORENCE STAGING FACILITY,2024-12-27 08:48:00,2024-12-27 08:48:00,Removed,2024-12-27 00:00:00,Removed,NaN,Male,...,2024-11-13 00:00:00,Border Patrol,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,00001bc128707c1bc0f44bfd6fcc3fa9c3d4f195
1,2025-09-17 10:00:00,2025-09-17 10:00:00,DALLAS F.O. HOLD,2025-09-18 19:02:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE",Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
2,2025-09-17 10:00:00,2025-09-18 22:43:00,BLUEBONNET DET FCLTY,2025-09-26 09:28:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Bluebonnet Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
3,2025-09-17 10:00:00,2025-09-26 17:25:00,PRAIRIELAND DETENTION CENTER,2025-09-27 12:03:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Prairieland Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-09-27 12:04:00,PINE PRAIRIE ICE PROCESSING CENTER,2025-10-02 15:20:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890979,2025-09-30 16:52:00,2025-09-30 16:52:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:52:00,2025-09-30 16:52:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890980,2025-09-30 16:56:00,2025-09-30 16:56:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:57:00,2025-09-30 16:57:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890981,2025-09-30 16:58:00,2025-09-30 16:58:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:58:00,2025-09-30 16:58:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890982,2025-09-30 16:59:00,2025-09-30 16:59:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:59:00,2025-09-30 16:59:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890983,2025-08-06 15:30:00,2025-08-06 15:30:00,MONTGOMERY PROCESSING CTR,2025-08-24 09:08:00,2025-08-24 09:08:00,Removed,2025-08-24 00:00:00,Removed,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Montgomery County, TX Sub Office",Houston Area of Responsibility,NaN

In [12]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df2_titled['Stay Book In Date Time'] = pd.to_datetime(df2_titled['Stay Book In Date Time'])

In [13]:
## create a subset of data for only 2022
##first: pull anything before 2023
df_2025pt2 = df2_titled[df2_titled['Stay Book In Date Time'] < '2026-01-01']

In [14]:
##now: pull anything after 2021 from the same subset. 
df_2025pt2 = df_2025pt2[df_2025pt2['Stay Book In Date Time'] > '2024-12-31']

In [15]:
df_2025pt2

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
1,2025-09-17 10:00:00,2025-09-17 10:00:00,DALLAS F.O. HOLD,2025-09-18 19:02:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE",Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
2,2025-09-17 10:00:00,2025-09-18 22:43:00,BLUEBONNET DET FCLTY,2025-09-26 09:28:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Bluebonnet Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
3,2025-09-17 10:00:00,2025-09-26 17:25:00,PRAIRIELAND DETENTION CENTER,2025-09-27 12:03:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Prairieland Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-09-27 12:04:00,PINE PRAIRIE ICE PROCESSING CENTER,2025-10-02 15:20:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
5,2025-07-15 12:50:00,2025-07-15 12:50:00,INDIANAPOLIS HOLD ROOM,2025-07-15 15:00:00,2025-07-25 06:08:00,Transferred,2025-07-25 00:00:00,Removed,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Indianapolis, IN Sub-Office",Chicago Area of Responsibility,0000518998357378d65efc37aee9a476ad110db1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890979,2025-09-30 16:52:00,2025-09-30 16:52:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:52:00,2025-09-30 16:52:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890980,2025-09-30 16:56:00,2025-09-30 16:56:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:57:00,2025-09-30 16:57:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890981,2025-09-30 16:58:00,2025-09-30 16:58:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:58:00,2025-09-30 16:58:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890982,2025-09-30 16:59:00,2025-09-30 16:59:00,LAREDO DETENTION CENTER HOLD ROOM,2025-09-30 16:59:00,2025-09-30 16:59:00,Voluntary Return,2025-09-30 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
890983,2025-08-06 15:30:00,2025-08-06 15:30:00,MONTGOMERY PROCESSING CTR,2025-08-24 09:08:00,2025-08-24 09:08:00,Removed,2025-08-24 00:00:00,Removed,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Montgomery County, TX Sub Office",Houston Area of Responsibility,NaN

In [16]:
##Let us do Extraction 1: 2022 ICE Detainers data
df_2025pt2.to_csv('FilteredData/2025ICEDetentions1.csv', index=False)

In [17]:
## let's pull data that i have downloaded. starting with the first file
df3 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/TEST2/RawData/Detentions/2026-ICLI-00005_Detentions_FY26_20260311_Redacted.xlsx')
df3

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICE Detentions FY2023 - FY2026YTD (10/01/2022 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628147,2026-03-10 18:05:00,2026-03-10 18:05:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:07:00,2026-03-10 18:07:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628148,2026-03-10 18:10:00,2026-03-10 18:10:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:10:00,2026-03-10 18:10:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628149,2026-03-10 16:10:00,2026-03-10 16:10:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,2026-02-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN
628150,2026-03-10 18:38:00,2026-03-10 18:38:00,ATLANTA DIST. HOLD RM,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE",Atlanta Area of Responsibility,NaN
628151,2026-03-10 20:35:00,2026-03-10 20:35:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN

In [18]:
#### As you can see: we don't need the first couple rows, it has unneeded rows. Let's remove the rows
df3 = df3.iloc[5:]
df3

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
6,2025-11-16 12:58:00,2025-11-16 12:58:00,AUSTIN DRO HOLD ROOM,2025-11-16 16:27:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Austin, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
7,2025-11-16 12:58:00,2025-11-16 16:41:00,T DON HUTTO DETENTION CENTER,2025-11-25 04:16:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Hutto, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
8,2025-11-16 12:58:00,2025-11-26 22:15:00,AZ REM OP COORD CENTER (AROCC),2025-11-28 00:50:00,2025-11-28 00:50:00,Removed,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
9,2025-09-17 10:00:00,2025-10-02 15:23:00,ALEXANDRIA STAGING FACILITY,2025-10-05 11:30:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628147,2026-03-10 18:05:00,2026-03-10 18:05:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:07:00,2026-03-10 18:07:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628148,2026-03-10 18:10:00,2026-03-10 18:10:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:10:00,2026-03-10 18:10:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628149,2026-03-10 16:10:00,2026-03-10 16:10:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,2026-02-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN
628150,2026-03-10 18:38:00,2026-03-10 18:38:00,ATLANTA DIST. HOLD RM,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE",Atlanta Area of Responsibility,NaN
628151,2026-03-10 20:35:00,2026-03-10 20:35:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN

In [19]:
## the first row is actually the header we want. Let's drop the header and put the actual header we want there
## create a new df, just to be safe
df3.columns = df3.iloc[0]
df3_titled = df3[1:].reset_index(drop=True)
df3_titled

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
0,2025-11-16 12:58:00,2025-11-16 12:58:00,AUSTIN DRO HOLD ROOM,2025-11-16 16:27:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Austin, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-16 12:58:00,2025-11-16 16:41:00,T DON HUTTO DETENTION CENTER,2025-11-25 04:16:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Hutto, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
2,2025-11-16 12:58:00,2025-11-26 22:15:00,AZ REM OP COORD CENTER (AROCC),2025-11-28 00:50:00,2025-11-28 00:50:00,Removed,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
3,2025-09-17 10:00:00,2025-10-02 15:23:00,ALEXANDRIA STAGING FACILITY,2025-10-05 11:30:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-10-05 11:36:00,River Correctional Center,2025-11-13 17:04:00,2025-11-13 17:04:00,Removed,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628141,2026-03-10 18:05:00,2026-03-10 18:05:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:07:00,2026-03-10 18:07:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628142,2026-03-10 18:10:00,2026-03-10 18:10:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:10:00,2026-03-10 18:10:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628143,2026-03-10 16:10:00,2026-03-10 16:10:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,2026-02-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN
628144,2026-03-10 18:38:00,2026-03-10 18:38:00,ATLANTA DIST. HOLD RM,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE",Atlanta Area of Responsibility,NaN
628145,2026-03-10 20:35:00,2026-03-10 20:35:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN

In [20]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df3_titled['Stay Book In Date Time'] = pd.to_datetime(df3_titled['Stay Book In Date Time'])

In [21]:
## create a subset of data
##first: pull anything
df_2025pt3 = df3_titled[df3_titled['Stay Book In Date Time'] < '2026-01-01']

In [22]:
##now: pull anything after 2024 from the same subset. 
df_2025pt3 = df_2025pt3[df_2025pt3['Stay Book In Date Time'] > '2024-12-31']

In [23]:
df_2025pt3

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
0,2025-11-16 12:58:00,2025-11-16 12:58:00,AUSTIN DRO HOLD ROOM,2025-11-16 16:27:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Austin, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-16 12:58:00,2025-11-16 16:41:00,T DON HUTTO DETENTION CENTER,2025-11-25 04:16:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Hutto, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
2,2025-11-16 12:58:00,2025-11-26 22:15:00,AZ REM OP COORD CENTER (AROCC),2025-11-28 00:50:00,2025-11-28 00:50:00,Removed,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
3,2025-09-17 10:00:00,2025-10-02 15:23:00,ALEXANDRIA STAGING FACILITY,2025-10-05 11:30:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-10-05 11:36:00,River Correctional Center,2025-11-13 17:04:00,2025-11-13 17:04:00,Removed,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627219,2025-12-31 16:22:00,2025-12-31 16:22:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-31 16:23:00,2025-12-31 16:23:00,Voluntary Return,2025-12-31 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627220,2025-12-31 16:29:00,2025-12-31 16:29:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-31 16:30:00,2025-12-31 16:30:00,Voluntary Return,2025-12-31 00:00:00,Voluntary Return,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627221,2025-12-31 16:29:00,2025-12-31 16:29:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-31 16:30:00,2025-12-31 16:30:00,Voluntary Return,2025-12-31 00:00:00,Voluntary Return,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627222,2025-12-31 16:44:00,2025-12-31 16:44:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-31 16:44:00,2025-12-31 16:44:00,Voluntary Return,2025-12-31 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627223,2025-12-31 17:20:00,2025-12-31 17:20:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-31 17:20:00,2025-12-31 17:20:00,Voluntary Return,2025-12-31 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN

In [24]:
df_2025pt3.to_csv('FilteredData/2025ICEDetentions2.csv', index=False)

In [25]:
df4 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/TEST2/RawData/Detentions/2026-ICLI-00005_Detentions_FY26_20260311_Redacted.xlsx')
df4

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICE Detentions FY2023 - FY2026YTD (10/01/2022 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628147,2026-03-10 18:05:00,2026-03-10 18:05:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:07:00,2026-03-10 18:07:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628148,2026-03-10 18:10:00,2026-03-10 18:10:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:10:00,2026-03-10 18:10:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628149,2026-03-10 16:10:00,2026-03-10 16:10:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,2026-02-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN
628150,2026-03-10 18:38:00,2026-03-10 18:38:00,ATLANTA DIST. HOLD RM,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE",Atlanta Area of Responsibility,NaN
628151,2026-03-10 20:35:00,2026-03-10 20:35:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN

In [26]:
df4 = df4.iloc[5:]
df4

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
6,2025-11-16 12:58:00,2025-11-16 12:58:00,AUSTIN DRO HOLD ROOM,2025-11-16 16:27:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Austin, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
7,2025-11-16 12:58:00,2025-11-16 16:41:00,T DON HUTTO DETENTION CENTER,2025-11-25 04:16:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Hutto, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
8,2025-11-16 12:58:00,2025-11-26 22:15:00,AZ REM OP COORD CENTER (AROCC),2025-11-28 00:50:00,2025-11-28 00:50:00,Removed,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
9,2025-09-17 10:00:00,2025-10-02 15:23:00,ALEXANDRIA STAGING FACILITY,2025-10-05 11:30:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628147,2026-03-10 18:05:00,2026-03-10 18:05:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:07:00,2026-03-10 18:07:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628148,2026-03-10 18:10:00,2026-03-10 18:10:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:10:00,2026-03-10 18:10:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628149,2026-03-10 16:10:00,2026-03-10 16:10:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,2026-02-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN
628150,2026-03-10 18:38:00,2026-03-10 18:38:00,ATLANTA DIST. HOLD RM,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE",Atlanta Area of Responsibility,NaN
628151,2026-03-10 20:35:00,2026-03-10 20:35:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN

In [27]:
df4.columns = df4.iloc[0]
df4_titled = df4[1:].reset_index(drop=True)
df4_titled

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
0,2025-11-16 12:58:00,2025-11-16 12:58:00,AUSTIN DRO HOLD ROOM,2025-11-16 16:27:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Austin, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-16 12:58:00,2025-11-16 16:41:00,T DON HUTTO DETENTION CENTER,2025-11-25 04:16:00,2025-11-28 00:50:00,Transferred,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Hutto, TX Sub Office",San Antonio Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
2,2025-11-16 12:58:00,2025-11-26 22:15:00,AZ REM OP COORD CENTER (AROCC),2025-11-28 00:50:00,2025-11-28 00:50:00,Removed,2025-11-28 00:00:00,Removed,NaN,Male,...,2023-09-30 00:00:00,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"FLORENCE, AZ, SERVICE PROCESSING CENTER (DOCKE...",Phoenix Area of Responsibility,0000004d7b875782a3b6f2b460f98c0750a5a899
3,2025-09-17 10:00:00,2025-10-02 15:23:00,ALEXANDRIA STAGING FACILITY,2025-10-05 11:30:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-10-05 11:36:00,River Correctional Center,2025-11-13 17:04:00,2025-11-13 17:04:00,Removed,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628141,2026-03-10 18:05:00,2026-03-10 18:05:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:07:00,2026-03-10 18:07:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628142,2026-03-10 18:10:00,2026-03-10 18:10:00,LAREDO DETENTION CENTER HOLD ROOM,2026-03-10 18:10:00,2026-03-10 18:10:00,Voluntary Return,2026-03-10 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
628143,2026-03-10 16:10:00,2026-03-10 16:10:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,2026-02-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN
628144,2026-03-10 18:38:00,2026-03-10 18:38:00,ATLANTA DIST. HOLD RM,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE",Atlanta Area of Responsibility,NaN
628145,2026-03-10 20:35:00,2026-03-10 20:35:00,PHOENIX DIST OFFICE,NaN,NaN,NaN,NaN,NaN,NaN,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE",Phoenix Area of Responsibility,NaN

In [28]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df4_titled['Stay Book In Date Time'] = pd.to_datetime(df1_titled['Stay Book In Date Time'])

In [29]:
df_2025pt4 = df4_titled[df4_titled['Stay Book In Date Time'] < '2026-01-01']

In [30]:
df_2025pt4 = df_2025pt4[df_2025pt4['Stay Book In Date Time'] > '2024-12-31']

In [31]:
df_2025pt4

Empty DataFrame
Columns: [Stay Book In Date Time, Book In Date Time, Detention Facility, Book Out Date Time, Stay Book Out Date Time, Detention Release Reason, Stay Book Out Date, Stay Release Reason, Religion, Gender, Marital Status, Ethnicity, Birth Country, Citizenship Country, Entry Status, Known Terrorist Yes No, Suspected Gang Yes No, MSC Charge, MSC Sentence Days, MSC Sentence Months, MSC Sentence Years, MSC Charge Code, Aggravated Felon Yes No, Offense INA 236C Yes No, Case INA 236C Yes No, Bond Posted Date, Bond Posted Amount, Case Status, Case Category, Final Order Yes No, Final Order Date, Case Threat Level, Detainee Classification, Final Charge, Departed Date, Departure Country, Initial Bond Set Amount, Initial Bond Set Date, Detention Facility Code, Birth Date, Birth Year, Book In Criminality, Race, Entry Date, Apprehension Final Program, MSC Charge Date, MSC Conviction Date, MSC Criminal Charge Status, MSC Criminal Charge Status Code, MSC Crime Class, Book In Site, Book In AOR, Anonymized Identifier]
Index: []

[0 rows x 53 columns]

In [33]:
pdList = [df_2025pt2, df_2025pt3]
df_All2025 = pd.concat(pdList)
df_All2025

5,Stay Book In Date Time,Book In Date Time,Detention Facility,Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,Gender,...,Entry Date,Apprehension Final Program,MSC Charge Date,MSC Conviction Date,MSC Criminal Charge Status,MSC Criminal Charge Status Code,MSC Crime Class,Book In Site,Book In AOR,Anonymized Identifier
1,2025-09-17 10:00:00,2025-09-17 10:00:00,DALLAS F.O. HOLD,2025-09-18 19:02:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE",Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
2,2025-09-17 10:00:00,2025-09-18 22:43:00,BLUEBONNET DET FCLTY,2025-09-26 09:28:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Bluebonnet Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
3,2025-09-17 10:00:00,2025-09-26 17:25:00,PRAIRIELAND DETENTION CENTER,2025-09-27 12:03:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,Prairieland Detention Center,Dallas Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
4,2025-09-17 10:00:00,2025-09-27 12:04:00,PINE PRAIRIE ICE PROCESSING CENTER,2025-10-02 15:20:00,2025-11-13 17:04:00,Transferred,2025-11-13 00:00:00,Removed,NaN,Male,...,2018-08-21 00:00:00,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Oakdale, LA Sub-Office",New Orleans Area of Responsibility,0000215186a4071ae5bc250f63e6baa60b286c30
5,2025-07-15 12:50:00,2025-07-15 12:50:00,INDIANAPOLIS HOLD ROOM,2025-07-15 15:00:00,2025-07-25 06:08:00,Transferred,2025-07-25 00:00:00,Removed,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Indianapolis, IN Sub-Office",Chicago Area of Responsibility,0000518998357378d65efc37aee9a476ad110db1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627219,2025-12-31 16:22:00,2025-12-31 16:22:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-31 16:23:00,2025-12-31 16:23:00,Voluntary Return,2025-12-31 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627220,2025-12-31 16:29:00,2025-12-31 16:29:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-31 16:30:00,2025-12-31 16:30:00,Voluntary Return,2025-12-31 00:00:00,Voluntary Return,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627221,2025-12-31 16:29:00,2025-12-31 16:29:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-31 16:30:00,2025-12-31 16:30:00,Voluntary Return,2025-12-31 00:00:00,Voluntary Return,NaN,Male,...,NaN,Fugitive Operations,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627222,2025-12-31 16:44:00,2025-12-31 16:44:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-31 16:44:00,2025-12-31 16:44:00,Voluntary Return,2025-12-31 00:00:00,Voluntary Return,NaN,Male,...,NaN,Detained Docket Control,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN
627223,2025-12-31 17:20:00,2025-12-31 17:20:00,LAREDO DETENTION CENTER HOLD ROOM,2025-12-31 17:20:00,2025-12-31 17:20:00,Voluntary Return,2025-12-31 00:00:00,Voluntary Return,NaN,Male,...,NaN,ERO Criminal Alien Program,NaN,NaN,NaN,NaN,NaN,"ERO - Laredo, TX Detention Center",Harlingen Area of Responsibility,NaN

In [34]:
df_All2025.to_csv('FilteredData/All2025ICEDetantionsData.csv', index=False)