### CONTEXT: 
So, I have the data from Sandra Fish on Colorado removals. Now, the code itself looks like it already starts with clean data for a specific year. But it uses data from Arrests, Detainers, Detentions, Encounters, AND removals. 

Now pulling that for each year for each category is a lot. So for the sake of time and exploration, i am first going to pull just 2025 data in this sheet so i can start analyzingand see if my analysis is correct. 

### In this notebook I will:
1. Pull data from the Deportation Data Project
2. Extract ICE Detainers for 2022, 2023, 2024, 2025, 2026
3. Clean the data for each year.

In [1]:
## import necessary libraries
import pandas as pd

### Extraction 1: 2025 detainers data

In [15]:
df1 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/TEST2/RawData/Detainers/2026-ICLI-00005_Detainers_FY24_20260311_Redacted.xlsx')
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Detainers Prepared FY2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147245,2024-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,RIVERSIDE COUNTY SHERIFF,RIVERCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147246,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,CAMBRIDGE POLICE DEPT,CAMPDMA,...,YES,Detainer Declined by LEA,A,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147247,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SUFFOLK HOC SBAY,SUFFOMA,...,YES,Superseding - New Form Issued,W,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147248,2024-09-30 00:00:00,TEXAS,Harlingen Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SAN JUAN POLICE DEPT.,SJUANTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
147249,2023-10-13 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,VENTURA CUSTODY CASE,VENHOLD,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN

In [16]:
#### As you can see: we don't need the first couple rows, it has unneeded rows. Let's remove the rows
df1 = df1.iloc[5:]
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
6,2024-05-11 00:00:00,NEW YORK,NaN,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,GOSHEN TOWN POLICE DEPARTMENT,GOSTPNY,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",00007dba409d3f00c75cd759758cb37d34872e8b
7,2024-03-12 00:00:00,FLORIDA,Miami Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",NICARAGUA,2024-08-22 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,TURNER GUIFORD KNIGHT (TGK) JAIL,TGKJLFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Bradenton, FL Sub Office","b(6), b(7)c",00035fe86dad009640790712354636d76b838c7c
8,2024-01-10 00:00:00,TEXAS,NaN,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",HONDURAS,2024-07-01 00:00:00,3-Voluntary Departure Confirmed,1 Convicted Criminal,HARRIS COUNTY JAIL,HARISTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Montgomery County, TX Sub Office","b(6), b(7)c",0003826317c1318abeffb0c01095af6825552b60
9,2023-11-03 00:00:00,FLORIDA,Miami Area of Responsibility,"BROWNSVILLE-MATAMOR, TX, POE",MEXICO,2023-12-20 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,PALM BEACH COUNTY JAIL,PALMBFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Stuart, FL Sub Office","b(6), b(7)c",00038f76045b3d1bb8b62d85365e29a9924a58f1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147245,2024-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,RIVERSIDE COUNTY SHERIFF,RIVERCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147246,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,CAMBRIDGE POLICE DEPT,CAMPDMA,...,YES,Detainer Declined by LEA,A,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147247,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SUFFOLK HOC SBAY,SUFFOMA,...,YES,Superseding - New Form Issued,W,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147248,2024-09-30 00:00:00,TEXAS,Harlingen Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SAN JUAN POLICE DEPT.,SJUANTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
147249,2023-10-13 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,VENTURA CUSTODY CASE,VENHOLD,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN

In [17]:
## the first row is actually the header we want. Let's drop the header and put the actual header we want there
## create a new df, just to be safe
df1.columns = df1.iloc[0]
df1_titled = df1[1:].reset_index(drop=True)
df1_titled

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
0,2024-05-11 00:00:00,NEW YORK,NaN,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,GOSHEN TOWN POLICE DEPARTMENT,GOSTPNY,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",00007dba409d3f00c75cd759758cb37d34872e8b
1,2024-03-12 00:00:00,FLORIDA,Miami Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",NICARAGUA,2024-08-22 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,TURNER GUIFORD KNIGHT (TGK) JAIL,TGKJLFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Bradenton, FL Sub Office","b(6), b(7)c",00035fe86dad009640790712354636d76b838c7c
2,2024-01-10 00:00:00,TEXAS,NaN,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",HONDURAS,2024-07-01 00:00:00,3-Voluntary Departure Confirmed,1 Convicted Criminal,HARRIS COUNTY JAIL,HARISTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Montgomery County, TX Sub Office","b(6), b(7)c",0003826317c1318abeffb0c01095af6825552b60
3,2023-11-03 00:00:00,FLORIDA,Miami Area of Responsibility,"BROWNSVILLE-MATAMOR, TX, POE",MEXICO,2023-12-20 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,PALM BEACH COUNTY JAIL,PALMBFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Stuart, FL Sub Office","b(6), b(7)c",00038f76045b3d1bb8b62d85365e29a9924a58f1
4,2023-10-13 00:00:00,VIRGINIA,Washington Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,CHESTERFIELD CO. JAIL,CHFLDVA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",0003ea57100be8d7c57c2a799f9fb12253d66e20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147239,2024-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,RIVERSIDE COUNTY SHERIFF,RIVERCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147240,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,CAMBRIDGE POLICE DEPT,CAMPDMA,...,YES,Detainer Declined by LEA,A,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147241,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SUFFOLK HOC SBAY,SUFFOMA,...,YES,Superseding - New Form Issued,W,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147242,2024-09-30 00:00:00,TEXAS,Harlingen Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SAN JUAN POLICE DEPT.,SJUANTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
147243,2023-10-13 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,VENTURA CUSTODY CASE,VENHOLD,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN

In [18]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df1_titled['Apprehension Date'] = pd.to_datetime(df1_titled['Apprehension Date'])

In [19]:
## create a subset of data for only 2022
##first: pull anything before 2023
df_2025pt1 = df1_titled[df1_titled['Apprehension Date'] < '2026-01-01']

In [20]:
##now: pull anything after 2021 from the same subset. 
df_2025pt1 = df_2025pt1[df_2025pt1['Apprehension Date'] > '2024-12-31']

In [22]:
##This is your 2025 ICE detainers data
df_2025pt1

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
40,2024-03-27 00:00:00,TEXAS,Dallas Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",EL SALVADOR,2025-10-07 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,IRVING POLICE DEPT.,IRVNGTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",00197c0df52a1bb3936347d6dc9816c997a2fb38
175,2024-04-23 00:00:00,PENNSYLVANIA,Philadelphia Area of Responsibility,NaN,NaN,NaN,ACTIVE,1 Convicted Criminal,ALLENWOOD (LOW) FCI,BOPALF,...,NO,Superseding - New Form Issued,W,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"WILLIAMSPORT, PA SUB OFFICE","b(6), b(7)c",00598db253c572c251447e853ad2a1484117e664
395,2024-04-07 00:00:00,TEXAS,NaN,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,TARRANT COUNTY JAIL,TARRATX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",00ce9184eada595b51b4436cefa3d3ba13458cc0
396,2024-07-12 00:00:00,INDIANA,Chicago Area of Responsibility,"HARLINGEN, TX, POE",MEXICO,2025-07-08 00:00:00,6-Deported/Removed - Deportability,1 Convicted Criminal,BARTHOLOMEW COUNTY SHERIFF/JAIL,BARTHIN,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Indianapolis, IN Sub-Office","b(6), b(7)c",00cef707a1eaf663563a3cffcb2894aeb00f93d4
408,2023-11-29 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,"BOSTON, MA (LOGAN), POE",CAPE VERDE,2026-01-03 00:00:00,6-Deported/Removed - Deportability,1 Convicted Criminal,SOUSA-BARANOWSKI CORR. CENTER,MASOBAR,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,Massachusetts Department of Correction,"b(6), b(7)c",00d60d67fb80d5b219ff261715b853071238ed6b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128750,2024-09-15 00:00:00,TEXAS,Dallas Area of Responsibility,"EL PASO, TX, POE",HONDURAS,2025-04-15 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,RANDALL COUNTY JAIL,RNDLLTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",ffac3f2ba254b316eaa966cfaa52bb4db99c2d0d
128845,2024-06-24 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,"SAN YSIDRO, CA, POE",MEXICO,2025-02-28 00:00:00,6-Deported/Removed - Deportability,1 Convicted Criminal,F.C.I. HERLONG,BOPHER,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"RENO, NV, DOCKET CONTROL OFFICE","b(6), b(7)c",ffd414d491288714654b1564f6d3da8caf73fc0a
128867,2024-01-11 00:00:00,LOUISIANA,New Orleans Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",MEXICO,2025-09-24 00:00:00,6-Deported/Removed - Deportability,1 Convicted Criminal,OAKDALE FED.CORR.INST.,BOPOAK,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"OAK - ERO - Oakdale, LA Sub-Office","b(6), b(7)c",ffe17e1d9e53fac2efa5c60fb7e2954c71441029
128876,2024-07-15 00:00:00,TEXAS,Dallas Area of Responsibility,"PASO DEL NORTE, TX, POE",MEXICO,2025-09-18 00:00:00,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,HOOD COUNTY SHERIFF'S DEPT.,HOODCTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",ffe6b4bd4bdbb922a346718462b1a581502dfd07
128925,2024-09-20 00:00:00,PENNSYLVANIA,Philadelphia Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",DOMINICAN REPUBLIC,2025-07-08 00:00:00,6-Deported/Removed - Deportability,1 Convicted Criminal,ALLENWOOD (LOW) FCI,BOPALF,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"WILLIAMSPORT, PA SUB OFFICE","b(6), b(7)c",ffff4cfea6d091a0c0b907d9ab71a5f4f4d4a7fe

In [24]:
##Let us do Extraction 1: 2022 ICE Detainers data
df_2025pt1.to_csv('FilteredData/2022ICEDetainersData1.csv', index=False)

In [28]:
##Ok, to be safe, let's check the file 2 in the zip folder for stray 2022 arrests and then start looking for 2023 data as well
df2 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/TEST2/RawData/Detainers/2026-ICLI-00005_Detainers_FY25_20260311_Redacted.xlsx')
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Detainers Prepared FY2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227123,2025-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SANTA CLARA CO JAIL/ELMWOOD,SCMENCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227124,2025-09-30 00:00:00,UTAH,Salt Lake City Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SALT LAKE COUNTY JAIL,SLSLCUT,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227125,2025-02-25 00:00:00,ARKANSAS,New Orleans Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,CLARK COUNTY DETENTION,CLARKAR,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Texarkana, AR Sub Office","b(6), b(7)c",NaN
227126,2025-01-25 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,HAYWOOD COUNTY JAIL,HAYWDNC,...,NO,Early Release,Z,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN
227127,2025-01-28 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,BUNCOMBE COUNTY DR.,BUNCONC,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN

In [29]:
#### As you can see: we don't need the first couple rows, it has unneeded rows. Let's remove the rows
df2 = df2.iloc[5:]
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
6,2025-05-08 00:00:00,NEW JERSEY,New York City Area of Responsibility,"EL PASO, TX, POE",SPAIN,2025-09-08 00:00:00,6-Deported/Removed - Deportability,2 Pending Criminal Charges,BERGEN COUNTY JAIL,BERGENJ,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"NEWARK, NJ, DOCKET CONTROL OFFICE","b(6), b(7)c",0002376e90e8512b938e102d96bb78306ceba284
7,2024-10-28 00:00:00,VIRGINIA,Washington Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,CHESAPEAKE CITY JAIL,CHSPKVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - NORFOLK,VA Sub Office","b(6), b(7)c",00025596228334361d821d68397ed1c641ab1f52
8,2024-10-31 00:00:00,VIRGINIA,Washington Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-07-14 00:00:00,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,CHESAPEAKE CITY JAIL,CHSPKVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - NORFOLK,VA Sub Office","b(6), b(7)c",00025596228334361d821d68397ed1c641ab1f52
9,2024-11-03 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,DOWNEY POLICE DEPT.,DWNEYCA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",000256e121d033cb3fc40b2aed8829ef8014f36f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227123,2025-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SANTA CLARA CO JAIL/ELMWOOD,SCMENCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227124,2025-09-30 00:00:00,UTAH,Salt Lake City Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SALT LAKE COUNTY JAIL,SLSLCUT,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227125,2025-02-25 00:00:00,ARKANSAS,New Orleans Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,CLARK COUNTY DETENTION,CLARKAR,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Texarkana, AR Sub Office","b(6), b(7)c",NaN
227126,2025-01-25 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,HAYWOOD COUNTY JAIL,HAYWDNC,...,NO,Early Release,Z,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN
227127,2025-01-28 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,BUNCOMBE COUNTY DR.,BUNCONC,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN

In [30]:
## the first row is actually the header we want. Let's drop the header and put the actual header we want there
## create a new df, just to be safe
df2.columns = df2.iloc[0]
df2_titled = df2[1:].reset_index(drop=True)
df2_titled

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
0,2025-05-08 00:00:00,NEW JERSEY,New York City Area of Responsibility,"EL PASO, TX, POE",SPAIN,2025-09-08 00:00:00,6-Deported/Removed - Deportability,2 Pending Criminal Charges,BERGEN COUNTY JAIL,BERGENJ,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"NEWARK, NJ, DOCKET CONTROL OFFICE","b(6), b(7)c",0002376e90e8512b938e102d96bb78306ceba284
1,2024-10-28 00:00:00,VIRGINIA,Washington Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,CHESAPEAKE CITY JAIL,CHSPKVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - NORFOLK,VA Sub Office","b(6), b(7)c",00025596228334361d821d68397ed1c641ab1f52
2,2024-10-31 00:00:00,VIRGINIA,Washington Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-07-14 00:00:00,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,CHESAPEAKE CITY JAIL,CHSPKVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - NORFOLK,VA Sub Office","b(6), b(7)c",00025596228334361d821d68397ed1c641ab1f52
3,2024-11-03 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,DOWNEY POLICE DEPT.,DWNEYCA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",000256e121d033cb3fc40b2aed8829ef8014f36f
4,2024-11-05 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,VENTURA COUNTY JAIL,VENTUCA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",000256e121d033cb3fc40b2aed8829ef8014f36f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227117,2025-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SANTA CLARA CO JAIL/ELMWOOD,SCMENCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227118,2025-09-30 00:00:00,UTAH,Salt Lake City Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SALT LAKE COUNTY JAIL,SLSLCUT,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227119,2025-02-25 00:00:00,ARKANSAS,New Orleans Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,CLARK COUNTY DETENTION,CLARKAR,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Texarkana, AR Sub Office","b(6), b(7)c",NaN
227120,2025-01-25 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,HAYWOOD COUNTY JAIL,HAYWDNC,...,NO,Early Release,Z,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN
227121,2025-01-28 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,BUNCOMBE COUNTY DR.,BUNCONC,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN

In [31]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df2_titled['Apprehension Date'] = pd.to_datetime(df2_titled['Apprehension Date'])

In [32]:
## create a subset of data for only 2022
##first: pull anything before 2023
df_2025pt2 = df2_titled[df2_titled['Apprehension Date'] < '2026-01-01']

In [33]:
##now: pull anything after 2021 from the same subset. 
df_2025pt2 = df_2025pt2[df_2025pt2['Apprehension Date'] > '2024-12-31']

In [34]:
df_2025pt2

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
0,2025-05-08 00:00:00,NEW JERSEY,New York City Area of Responsibility,"EL PASO, TX, POE",SPAIN,2025-09-08 00:00:00,6-Deported/Removed - Deportability,2 Pending Criminal Charges,BERGEN COUNTY JAIL,BERGENJ,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"NEWARK, NJ, DOCKET CONTROL OFFICE","b(6), b(7)c",0002376e90e8512b938e102d96bb78306ceba284
2,2024-10-31 00:00:00,VIRGINIA,Washington Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-07-14 00:00:00,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,CHESAPEAKE CITY JAIL,CHSPKVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - NORFOLK,VA Sub Office","b(6), b(7)c",00025596228334361d821d68397ed1c641ab1f52
8,2025-06-01 00:00:00,FLORIDA,Miami Area of Responsibility,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,MARION COUNTY JAIL,MARIOFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ORLANDO, FL, DOCKET CONTROL OFFICE","b(6), b(7)c",00033edbdcdeece6e9a14515afbf955bf03d8032
10,2025-05-27 00:00:00,NEW JERSEY,Newark Area of Responsibility,"HOUSTON, TX, POE",HONDURAS,2025-09-19 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,OCEAN COUNTY JAIL,OCEANNJ,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,ICE ERO - MOUNT LAUREL NJ SUB-OFC,"b(6), b(7)c",00035ca115ef0bcaa06937b5e612ae114f1076e6
11,2025-06-08 00:00:00,FLORIDA,Miami Area of Responsibility,NaN,NaN,NaN,A-Proceedings Terminated,2 Pending Criminal Charges,ORANGE COUNTY JAIL,ORANGFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ORLANDO, FL, DOCKET CONTROL OFFICE","b(6), b(7)c",0003b5b9579328da291370c83d5c5180c59917aa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223860,2025-08-24 00:00:00,TEXAS,Harlingen Area of Responsibility,"HIDALGO, TX, POE",MEXICO,2025-08-25 00:00:00,9-VR Witnessed,3 Other Immigration Violator,HIDALGO COUNTY SHERIFF'S JAIL,HIDALTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - EDINBURG, TX, SUB-OFFICE","b(6), b(7)c",NaN
225815,2025-09-18 00:00:00,TEXAS,Dallas Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,MOORE COUNTY SHERIFF,MOORETX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
226250,2025-09-22 00:00:00,FLORIDA,Miami Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,POLK COUNTY JAIL,POLKJFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"TAMPA, FL, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
226259,2025-09-22 00:00:00,TEXAS,Dallas Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,DALLAM COUNTY SHERIFF,DALLMTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Amarillo, TX Sub-Office","b(6), b(7)c",NaN
226408,2025-09-23 00:00:00,FLORIDA,Miami Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,MONROE COUNTY JAIL,MONROFL,...,YES,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"MARATHON, FL, BORDER PATROL STATION","b(6), b(7)c",NaN

In [35]:
##Let us do Extraction 1: 2022 ICE Detainers data
df_2025pt2.to_csv('FilteredData/2022ICEDetainersData2.csv', index=False)