### CONTEXT: 
So, I have the data from Sandra Fish on Colorado removals. Now, the code itself looks like it already starts with clean data for a specific year. But it uses data from Arrests, Detainers, Detentions, Encounters, AND removals. 

Now pulling that for each year for each category is a lot. So for the sake of time and exploration, i am first going to pull just 2025 data in this sheet so i can start analyzingand see if my analysis is correct. 

### In this notebook I will:
1. Pull data from the Deportation Data Project
2. Extract ICE Detainers for 2025

In [1]:
## import necessary libraries
import pandas as pd

### Extraction 1: 2025 detainers data

In [39]:
df1 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/TEST2/RawData/Detainers/2026-ICLI-00005_Detainers_FY24_20260311_Redacted.xlsx')
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Detainers Prepared FY2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147245,2024-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,RIVERSIDE COUNTY SHERIFF,RIVERCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147246,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,CAMBRIDGE POLICE DEPT,CAMPDMA,...,YES,Detainer Declined by LEA,A,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147247,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SUFFOLK HOC SBAY,SUFFOMA,...,YES,Superseding - New Form Issued,W,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147248,2024-09-30 00:00:00,TEXAS,Harlingen Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SAN JUAN POLICE DEPT.,SJUANTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
147249,2023-10-13 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,VENTURA CUSTODY CASE,VENHOLD,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN

In [40]:
#### As you can see: we don't need the first couple rows, it has unneeded rows. Let's remove the rows
df1 = df1.iloc[5:]
df1

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
6,2024-05-11 00:00:00,NEW YORK,NaN,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,GOSHEN TOWN POLICE DEPARTMENT,GOSTPNY,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",00007dba409d3f00c75cd759758cb37d34872e8b
7,2024-03-12 00:00:00,FLORIDA,Miami Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",NICARAGUA,2024-08-22 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,TURNER GUIFORD KNIGHT (TGK) JAIL,TGKJLFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Bradenton, FL Sub Office","b(6), b(7)c",00035fe86dad009640790712354636d76b838c7c
8,2024-01-10 00:00:00,TEXAS,NaN,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",HONDURAS,2024-07-01 00:00:00,3-Voluntary Departure Confirmed,1 Convicted Criminal,HARRIS COUNTY JAIL,HARISTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Montgomery County, TX Sub Office","b(6), b(7)c",0003826317c1318abeffb0c01095af6825552b60
9,2023-11-03 00:00:00,FLORIDA,Miami Area of Responsibility,"BROWNSVILLE-MATAMOR, TX, POE",MEXICO,2023-12-20 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,PALM BEACH COUNTY JAIL,PALMBFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Stuart, FL Sub Office","b(6), b(7)c",00038f76045b3d1bb8b62d85365e29a9924a58f1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147245,2024-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,RIVERSIDE COUNTY SHERIFF,RIVERCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147246,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,CAMBRIDGE POLICE DEPT,CAMPDMA,...,YES,Detainer Declined by LEA,A,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147247,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SUFFOLK HOC SBAY,SUFFOMA,...,YES,Superseding - New Form Issued,W,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147248,2024-09-30 00:00:00,TEXAS,Harlingen Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SAN JUAN POLICE DEPT.,SJUANTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
147249,2023-10-13 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,VENTURA CUSTODY CASE,VENHOLD,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN

In [41]:
## the first row is actually the header we want. Let's drop the header and put the actual header we want there
## create a new df, just to be safe
df1.columns = df1.iloc[0]
df1_titled = df1[1:].reset_index(drop=True)
df1_titled

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
0,2024-05-11 00:00:00,NEW YORK,NaN,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,GOSHEN TOWN POLICE DEPARTMENT,GOSTPNY,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",00007dba409d3f00c75cd759758cb37d34872e8b
1,2024-03-12 00:00:00,FLORIDA,Miami Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",NICARAGUA,2024-08-22 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,TURNER GUIFORD KNIGHT (TGK) JAIL,TGKJLFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Bradenton, FL Sub Office","b(6), b(7)c",00035fe86dad009640790712354636d76b838c7c
2,2024-01-10 00:00:00,TEXAS,NaN,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",HONDURAS,2024-07-01 00:00:00,3-Voluntary Departure Confirmed,1 Convicted Criminal,HARRIS COUNTY JAIL,HARISTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Montgomery County, TX Sub Office","b(6), b(7)c",0003826317c1318abeffb0c01095af6825552b60
3,2023-11-03 00:00:00,FLORIDA,Miami Area of Responsibility,"BROWNSVILLE-MATAMOR, TX, POE",MEXICO,2023-12-20 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,PALM BEACH COUNTY JAIL,PALMBFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - Stuart, FL Sub Office","b(6), b(7)c",00038f76045b3d1bb8b62d85365e29a9924a58f1
4,2023-10-13 00:00:00,VIRGINIA,Washington Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,CHESTERFIELD CO. JAIL,CHFLDVA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",0003ea57100be8d7c57c2a799f9fb12253d66e20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147239,2024-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,RIVERSIDE COUNTY SHERIFF,RIVERCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147240,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,CAMBRIDGE POLICE DEPT,CAMPDMA,...,YES,Detainer Declined by LEA,A,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147241,2024-09-30 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SUFFOLK HOC SBAY,SUFFOMA,...,YES,Superseding - New Form Issued,W,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
147242,2024-09-30 00:00:00,TEXAS,Harlingen Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SAN JUAN POLICE DEPT.,SJUANTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
147243,2023-10-13 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,VENTURA CUSTODY CASE,VENHOLD,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN

In [42]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df1_titled['Departed Date'] = pd.to_datetime(df1_titled['Departed Date'])

In [43]:
## create a subset of data for only 2022
##first: pull anything before 2023
df_2025pt1 = df1_titled[df1_titled['Departed Date'] < '2026-01-01']

In [44]:
##now: pull anything after 2021 from the same subset. 
df_2025pt1 = df_2025pt1[df_2025pt1['Departed Date'] > '2024-12-31']

In [45]:
##This is your 2025 ICE detainers data
df_2025pt1

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
28,2024-07-08 00:00:00,ARKANSAS,New Orleans Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-04-01,8-Excluded/Removed - Inadmissibility,3 Other Immigration Violator,PULASKI COUNTY REG.DET.FAC.,PULASAR,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",00103f3e74679b755da13514ecf999d52ef39c4e
35,2024-01-28 00:00:00,VIRGINIA,Washington Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-02-26,6-Deported/Removed - Deportability,1 Convicted Criminal,PRINCE WILLIAM,PWILLVA,...,NO,Detainer Declined by LEA,A,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",0015da563be4d6695f33804021144210bade49dd
40,2024-03-27 00:00:00,TEXAS,Dallas Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",EL SALVADOR,2025-10-07,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,IRVING POLICE DEPT.,IRVNGTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",00197c0df52a1bb3936347d6dc9816c997a2fb38
46,2024-06-10 00:00:00,ARIZONA,Phoenix Area of Responsibility,"NOGALES, AZ, POE",MEXICO,2025-01-08,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,MARICOPA COUNTY JAIL,MCFAJAZ,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE","b(6), b(7)c",001d1303978e35d722d597f0e15f5692dd5286df
47,2024-08-12 00:00:00,ARIZONA,Phoenix Area of Responsibility,"NOGALES, AZ, POE",MEXICO,2025-01-08,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,US MARSHAL - PHOENIX,USMPHO,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE","b(6), b(7)c",001d1303978e35d722d597f0e15f5692dd5286df
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141864,2024-06-28 00:00:00,VIRGINIA,Washington Area of Responsibility,"WASHINGTON, DC, DULLES AIRPORT, POE",GUATEMALA,2025-02-23,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,ARLINGTON CO JAIL,ARLCOVA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
143257,2024-07-22 00:00:00,VIRGINIA,Washington Area of Responsibility,"WASHINGTON, DC, DULLES AIRPORT, POE",GUATEMALA,2025-02-23,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,ALEXANDRIA CITY JAIL,ALEXAVA,...,NO,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"WASHINGTON, DC, Docket Control Office","b(6), b(7)c",NaN
144337,2024-08-11 00:00:00,MASSACHUSETTS,Boston Area of Responsibility,"LOGAN INTERNATIONAL AIRPORT, BOSTON MA, POE",DOMINICAN REPUBLIC,2025-05-08,6-Deported/Removed - Deportability,2 Pending Criminal Charges,"ESSEX CO. JAIL, MIDDLETON",ESSEXMA,...,NO,Detainer Declined by LEA,A,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"BOSTON, MA, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
145107,2024-08-25 00:00:00,GEORGIA,Atlanta Area of Responsibility,"HARLINGEN, TX, POE",MEXICO,2025-07-18,6-Deported/Removed - Deportability,2 Pending Criminal Charges,ATKINSON COUNTY JAIL,ATKNSGA,...,YES,Booked into Detention,B,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
146281,2024-09-13 00:00:00,MARYLAND,NaN,NaN,NaN,2025-05-28,7-Died,2 Pending Criminal Charges,PRINCE GEORGES CO DET CEN,PRINCMD,...,NO,Insufficient Notice to ICE,O,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"BALTIMORE, MD, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN

In [48]:
##Let us do Extraction 1: 2025 ICE Detainers data
df_2025pt1.to_csv('FilteredData/2025ICEDetainersData1.csv', index=False)

In [49]:
##Ok, to be safe, let's check the file 2 in the zip folder for stray 2022 arrests and then start looking for 2023 data as well
df2 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/TEST2/RawData/Detainers/2026-ICLI-00005_Detainers_FY25_20260311_Redacted.xlsx')
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Detainers Prepared FY2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227123,2025-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SANTA CLARA CO JAIL/ELMWOOD,SCMENCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227124,2025-09-30 00:00:00,UTAH,Salt Lake City Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SALT LAKE COUNTY JAIL,SLSLCUT,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227125,2025-02-25 00:00:00,ARKANSAS,New Orleans Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,CLARK COUNTY DETENTION,CLARKAR,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Texarkana, AR Sub Office","b(6), b(7)c",NaN
227126,2025-01-25 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,HAYWOOD COUNTY JAIL,HAYWDNC,...,NO,Early Release,Z,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN
227127,2025-01-28 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,BUNCOMBE COUNTY DR.,BUNCONC,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN

In [50]:
#### As you can see: we don't need the first couple rows, it has unneeded rows. Let's remove the rows
df2 = df2.iloc[5:]
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
6,2025-05-08 00:00:00,NEW JERSEY,New York City Area of Responsibility,"EL PASO, TX, POE",SPAIN,2025-09-08 00:00:00,6-Deported/Removed - Deportability,2 Pending Criminal Charges,BERGEN COUNTY JAIL,BERGENJ,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"NEWARK, NJ, DOCKET CONTROL OFFICE","b(6), b(7)c",0002376e90e8512b938e102d96bb78306ceba284
7,2024-10-28 00:00:00,VIRGINIA,Washington Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,CHESAPEAKE CITY JAIL,CHSPKVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - NORFOLK,VA Sub Office","b(6), b(7)c",00025596228334361d821d68397ed1c641ab1f52
8,2024-10-31 00:00:00,VIRGINIA,Washington Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-07-14 00:00:00,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,CHESAPEAKE CITY JAIL,CHSPKVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - NORFOLK,VA Sub Office","b(6), b(7)c",00025596228334361d821d68397ed1c641ab1f52
9,2024-11-03 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,DOWNEY POLICE DEPT.,DWNEYCA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",000256e121d033cb3fc40b2aed8829ef8014f36f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227123,2025-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SANTA CLARA CO JAIL/ELMWOOD,SCMENCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227124,2025-09-30 00:00:00,UTAH,Salt Lake City Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SALT LAKE COUNTY JAIL,SLSLCUT,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227125,2025-02-25 00:00:00,ARKANSAS,New Orleans Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,CLARK COUNTY DETENTION,CLARKAR,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Texarkana, AR Sub Office","b(6), b(7)c",NaN
227126,2025-01-25 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,HAYWOOD COUNTY JAIL,HAYWDNC,...,NO,Early Release,Z,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN
227127,2025-01-28 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,BUNCOMBE COUNTY DR.,BUNCONC,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN

In [51]:
## the first row is actually the header we want. Let's drop the header and put the actual header we want there
## create a new df, just to be safe
df2.columns = df2.iloc[0]
df2_titled = df2[1:].reset_index(drop=True)
df2_titled

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
0,2025-05-08 00:00:00,NEW JERSEY,New York City Area of Responsibility,"EL PASO, TX, POE",SPAIN,2025-09-08 00:00:00,6-Deported/Removed - Deportability,2 Pending Criminal Charges,BERGEN COUNTY JAIL,BERGENJ,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"NEWARK, NJ, DOCKET CONTROL OFFICE","b(6), b(7)c",0002376e90e8512b938e102d96bb78306ceba284
1,2024-10-28 00:00:00,VIRGINIA,Washington Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,CHESAPEAKE CITY JAIL,CHSPKVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - NORFOLK,VA Sub Office","b(6), b(7)c",00025596228334361d821d68397ed1c641ab1f52
2,2024-10-31 00:00:00,VIRGINIA,Washington Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-07-14 00:00:00,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,CHESAPEAKE CITY JAIL,CHSPKVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - NORFOLK,VA Sub Office","b(6), b(7)c",00025596228334361d821d68397ed1c641ab1f52
3,2024-11-03 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,DOWNEY POLICE DEPT.,DWNEYCA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",000256e121d033cb3fc40b2aed8829ef8014f36f
4,2024-11-05 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,VENTURA COUNTY JAIL,VENTUCA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",000256e121d033cb3fc40b2aed8829ef8014f36f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227117,2025-09-30 00:00:00,CALIFORNIA,San Francisco Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SANTA CLARA CO JAIL/ELMWOOD,SCMENCA,...,YES,"No longer in State, Local, or Federal Custody",G,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227118,2025-09-30 00:00:00,UTAH,Salt Lake City Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,SALT LAKE COUNTY JAIL,SLSLCUT,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN
227119,2025-02-25 00:00:00,ARKANSAS,New Orleans Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,CLARK COUNTY DETENTION,CLARKAR,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Texarkana, AR Sub Office","b(6), b(7)c",NaN
227120,2025-01-25 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,HAYWOOD COUNTY JAIL,HAYWDNC,...,NO,Early Release,Z,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN
227121,2025-01-28 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,BUNCOMBE COUNTY DR.,BUNCONC,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Henderson, NC Sub Office","b(6), b(7)c",NaN

In [52]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df2_titled['Departed Date'] = pd.to_datetime(df2_titled['Departed Date'])

In [53]:
## create a subset of data for only 2022
##first: pull anything before 2023
df_2025pt2 = df2_titled[df2_titled['Departed Date'] < '2026-01-01']

In [54]:
##now: pull anything after 2021 from the same subset. 
df_2025pt2 = df_2025pt2[df_2025pt2['Departed Date'] > '2024-12-31']

In [55]:
df_2025pt2

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
0,2025-05-08 00:00:00,NEW JERSEY,New York City Area of Responsibility,"EL PASO, TX, POE",SPAIN,2025-09-08,6-Deported/Removed - Deportability,2 Pending Criminal Charges,BERGEN COUNTY JAIL,BERGENJ,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"NEWARK, NJ, DOCKET CONTROL OFFICE","b(6), b(7)c",0002376e90e8512b938e102d96bb78306ceba284
2,2024-10-31 00:00:00,VIRGINIA,Washington Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-07-14,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,CHESAPEAKE CITY JAIL,CHSPKVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"ERO - NORFOLK,VA Sub Office","b(6), b(7)c",00025596228334361d821d68397ed1c641ab1f52
9,2025-05-27 00:00:00,NEW JERSEY,Newark Area of Responsibility,"HOUSTON, TX, POE",HONDURAS,2025-09-19,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,OCEAN COUNTY JAIL,OCEANNJ,...,YES,Booked into Detention,B,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",00035ca115ef0bcaa06937b5e612ae114f1076e6
10,2025-05-27 00:00:00,NEW JERSEY,Newark Area of Responsibility,"HOUSTON, TX, POE",HONDURAS,2025-09-19,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,OCEAN COUNTY JAIL,OCEANNJ,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,ICE ERO - MOUNT LAUREL NJ SUB-OFC,"b(6), b(7)c",00035ca115ef0bcaa06937b5e612ae114f1076e6
13,2024-12-09 00:00:00,TEXAS,El Paso Area of Responsibility,"SAN YSIDRO, CA, POE",MEXICO,2025-09-09,8-Excluded/Removed - Inadmissibility,3 Other Immigration Violator,EL PASO COUNTY JAIL (TX),ELPCOTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Otero County Processing Center,"b(6), b(7)c",00046a7b75893dc7f4e084fde3d4e0d4aab014d5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223860,2025-08-24 00:00:00,TEXAS,Harlingen Area of Responsibility,"HIDALGO, TX, POE",MEXICO,2025-08-25,9-VR Witnessed,3 Other Immigration Violator,HIDALGO COUNTY SHERIFF'S JAIL,HIDALTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - EDINBURG, TX, SUB-OFFICE","b(6), b(7)c",NaN
224003,2025-08-25 00:00:00,TEXAS,NaN,"HOUSTON, TX (AIRPORT), POE",GUATEMALA,2025-12-20,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,HARRIS COUNTY JAIL,HARISTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Montgomery County, TX Sub Office","b(6), b(7)c",NaN
224016,2025-08-26 00:00:00,TEXAS,NaN,"HOUSTON, TX (AIRPORT), POE",GUATEMALA,2025-11-08,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,HARRIS COUNTY JAIL,HARISTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Montgomery County, TX Sub Office","b(6), b(7)c",NaN
226990,2025-09-29 00:00:00,CALIFORNIA,San Diego Area of Responsibility,"SAN YSIDRO, CA, POE",MEXICO,2025-12-13,8-Excluded/Deported/Removed,3 Other Immigration Violator,SAN DIEGO COUNTY JAIL,SNDCOCA,...,NO,Detainer Declined by LEA,A,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Imperial, CA Sub Office","b(6), b(7)c",NaN
227029,2025-09-29 00:00:00,FLORIDA,Miami Area of Responsibility,"HARLINGEN, TX, POE",MEXICO,2025-10-09,3-Voluntary Departure Confirmed,2 Pending Criminal Charges,POLK COUNTY JAIL,POLKJFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"KROME, MIAMI, FL, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN

In [56]:
##Let us do Extraction 1: 2022 ICE Detainers data
df_2025pt2.to_csv('FilteredData/2025ICEDetainersData2.csv', index=False)

In [57]:
## let's pull data that i have downloaded. starting with the first file
df3 = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/TEST2/RawData/Detainers/2026-ICLI-00005_Detainers_FY26_20260311_Redacted.xlsx')
df3

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 – 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Detainers Prepared FY2026YTD (10/01/2025 -...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112840,2026-03-11 00:00:00,FLORIDA,Miami Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,ST. LUCIE COUNTY JAIL,STLUCFL,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"KROME, MIAMI, FL, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112841,2026-03-10 00:00:00,TEXAS,Dallas Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,ELLIS COUNTY SHERIFF'S DEPT.,ELLISTX,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112842,2026-03-11 00:00:00,GEORGIA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,COBB CO SHERIFFS OFC ADULT DET CTR,COBBJGA,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112843,2026-03-10 00:00:00,GEORGIA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,COWETA COUNTY SHERIFF,CWETAGA,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112844,2026-03-10 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,ORANGE COUNTY JAIL,ORANGCA,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN

In [58]:
#### As you can see: we don't need the first couple rows, it has unneeded rows. Let's remove the rows
df3 = df3.iloc[5:]
df3

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
6,2025-10-27 00:00:00,OREGON,Seattle Area of Responsibility,NaN,NaN,NaN,ACTIVE,1 Convicted Criminal,SHERIDAN FED.CORR.INST.,BOPSHE,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"PORTLAND, OR, DOCKET CONTROL OFFICE","b(6), b(7)c",0000eccad0ce73c253ff57e650ecdcee278bf1fd
7,2025-10-30 00:00:00,UTAH,NaN,"NOGALES, AZ, POE",MEXICO,2025-12-20 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,US MARSHALS - UTAH,USMUT,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE","b(6), b(7)c",000123c8701799c3f1c69fc5b9237441afcf6161
8,2026-02-14 00:00:00,FLORIDA,Miami Area of Responsibility,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,LEE COUNTY JAIL,LEECOFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,NaN,"b(6), b(7)c",0001c9598ba1c9866270b617f4c82ff2e04d3e29
9,2026-02-12 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,MECKLENBURG COUNTY JAIL CENTRAL,MECKLN2,...,NO,USC or Presumptive Claim to US Citizenship,X,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Charlotte, NC Sub-Office","b(6), b(7)c",0003948dedafe23c39ce1dfcf700910354327e62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112840,2026-03-11 00:00:00,FLORIDA,Miami Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,ST. LUCIE COUNTY JAIL,STLUCFL,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"KROME, MIAMI, FL, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112841,2026-03-10 00:00:00,TEXAS,Dallas Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,ELLIS COUNTY SHERIFF'S DEPT.,ELLISTX,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112842,2026-03-11 00:00:00,GEORGIA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,COBB CO SHERIFFS OFC ADULT DET CTR,COBBJGA,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112843,2026-03-10 00:00:00,GEORGIA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,COWETA COUNTY SHERIFF,CWETAGA,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112844,2026-03-10 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,ORANGE COUNTY JAIL,ORANGCA,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN

In [59]:
## the first row is actually the header we want. Let's drop the header and put the actual header we want there
## create a new df, just to be safe
df3.columns = df3.iloc[0]
df3_titled = df3[1:].reset_index(drop=True)
df3_titled

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
0,2025-10-27 00:00:00,OREGON,Seattle Area of Responsibility,NaN,NaN,NaN,ACTIVE,1 Convicted Criminal,SHERIDAN FED.CORR.INST.,BOPSHE,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"PORTLAND, OR, DOCKET CONTROL OFFICE","b(6), b(7)c",0000eccad0ce73c253ff57e650ecdcee278bf1fd
1,2025-10-30 00:00:00,UTAH,NaN,"NOGALES, AZ, POE",MEXICO,2025-12-20 00:00:00,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,US MARSHALS - UTAH,USMUT,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE","b(6), b(7)c",000123c8701799c3f1c69fc5b9237441afcf6161
2,2026-02-14 00:00:00,FLORIDA,Miami Area of Responsibility,NaN,NaN,NaN,ACTIVE,2 Pending Criminal Charges,LEE COUNTY JAIL,LEECOFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,NaN,"b(6), b(7)c",0001c9598ba1c9866270b617f4c82ff2e04d3e29
3,2026-02-12 00:00:00,NORTH CAROLINA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,1 Convicted Criminal,MECKLENBURG COUNTY JAIL CENTRAL,MECKLN2,...,NO,USC or Presumptive Claim to US Citizenship,X,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Charlotte, NC Sub-Office","b(6), b(7)c",0003948dedafe23c39ce1dfcf700910354327e62
4,2025-10-28 00:00:00,TEXAS,NaN,"HIDALGO, TX, POE",MEXICO,2025-11-05 00:00:00,6-Deported/Removed - Deportability,3 Other Immigration Violator,GALVESTON COUNTY SHERIFF,GALVETX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"HOUSTON, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",0006023d014d189c1b0dd2ff30a1c27b3b31892b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112834,2026-03-11 00:00:00,FLORIDA,Miami Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,ST. LUCIE COUNTY JAIL,STLUCFL,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"KROME, MIAMI, FL, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112835,2026-03-10 00:00:00,TEXAS,Dallas Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,ELLIS COUNTY SHERIFF'S DEPT.,ELLISTX,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112836,2026-03-11 00:00:00,GEORGIA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,2 Pending Criminal Charges,COBB CO SHERIFFS OFC ADULT DET CTR,COBBJGA,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112837,2026-03-10 00:00:00,GEORGIA,Atlanta Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,COWETA COUNTY SHERIFF,CWETAGA,...,NO,NaN,NaN,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ATLANTA, GA, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
112838,2026-03-10 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,NaN,NaN,NaN,NaN,3 Other Immigration Violator,ORANGE COUNTY JAIL,ORANGCA,...,YES,NaN,NaN,NaN,NaN,I247G - Request for Advance Notification of Re...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",NaN

In [60]:
## to be safe, let's turn the time, which is what we need, into datetime
## turn the column into datetime
df3_titled['Departed Date'] = pd.to_datetime(df3_titled['Departed Date'])

In [61]:
## create a subset of data
##first: pull anything
df_2025pt3 = df3_titled[df3_titled['Departed Date'] < '2026-01-01']

In [62]:
##now: pull anything after 2024 from the same subset. 
df_2025pt3 = df_2025pt3[df_2025pt3['Departed Date'] > '2024-12-31']

In [63]:
df_2025pt3

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
1,2025-10-30 00:00:00,UTAH,NaN,"NOGALES, AZ, POE",MEXICO,2025-12-20,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,US MARSHALS - UTAH,USMUT,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE","b(6), b(7)c",000123c8701799c3f1c69fc5b9237441afcf6161
4,2025-10-28 00:00:00,TEXAS,NaN,"HIDALGO, TX, POE",MEXICO,2025-11-05,6-Deported/Removed - Deportability,3 Other Immigration Violator,GALVESTON COUNTY SHERIFF,GALVETX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"HOUSTON, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",0006023d014d189c1b0dd2ff30a1c27b3b31892b
27,2025-11-20 00:00:00,FLORIDA,Miami Area of Responsibility,"PHOENIX, AZ, POE",VENEZUELA,2025-12-03,3-Voluntary Departure Confirmed,2 Pending Criminal Charges,HILLSBOROUGH COUNTY JAIL,HICOJFL,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"TAMPA, FL, DOCKET CONTROL OFFICE","b(6), b(7)c",00116109bb3123818f040adddce95629116a1379
29,2025-12-05 00:00:00,VIRGINIA,Washington Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-12-12,3-Voluntary Departure Confirmed,2 Pending Criminal Charges,CULPEPER CO. ADULT DET. CENTER,CULPEVA,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Harrisonburg, VA Sub Office","b(6), b(7)c",0011a60eb13c05f1a107c9ba6eeac91296d3e263
40,2025-10-02 00:00:00,PUERTO RICO,Miami Area of Responsibility,Luis Munoz Marin Int'l Airport,DOMINICAN REPUBLIC,2025-11-03,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,BAYAMON REGIONAL JAIL.,PRBAYAM,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"SAN JUAN, PR, SERVICE PROCESSING CENTER (DOCKE...","b(6), b(7)c",001b481adfd9620344058c6b0a6d7c91f301eb69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96824,2025-11-02 00:00:00,TEXAS,Dallas Area of Responsibility,"DALLAS, TX, POE",HONDURAS,2025-12-17,3-Voluntary Departure Confirmed,2 Pending Criminal Charges,GRAND PRAIRIE CITY JAIL,GRPRATX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",fff6a919573b3801f4824bfed092235e32c4f9d7
96834,2025-12-01 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,"SAN YSIDRO, CA, POE",MEXICO,2025-12-23,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,LOS ANGELES MET.DET.CTR.,BOPLOS,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"LOS ANGELES, CA, DOCKET CONTROL OFFICE","b(6), b(7)c",fffb1d13fc1ac1fffd53bfcf81c6d66305e4863b
98216,2025-10-15 00:00:00,TEXAS,NaN,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",COLOMBIA,2025-11-28,3-Voluntary Departure Confirmed,2 Pending Criminal Charges,HARRIS COUNTY JAIL,HARISTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Montgomery County, TX Sub Office","b(6), b(7)c",NaN
101881,2025-11-22 00:00:00,TEXAS,Harlingen Area of Responsibility,"LAREDO, TX, POE",MEXICO,2025-11-25,9-VR Witnessed,2 Pending Criminal Charges,WEBB COUNTY JAIL,WEBCOTX,...,NO,Case Closed,C,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
103624,2025-12-12 00:00:00,TEXAS,Harlingen Area of Responsibility,"LAREDO, TX, POE",MEXICO,2025-12-15,9-VR Witnessed,2 Pending Criminal Charges,WEBB COUNTY JAIL,WEBCOTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Laredo, TX Detention Center","b(6), b(7)c",NaN

In [64]:
df_2025pt3.to_csv('FilteredData/2025ICEDetainersData3.csv', index=False)

In [65]:
pdList = [df_2025pt1, df_2025pt2, df_2025pt3]
df_All2025 = pd.concat(pdList)
df_All2025

5,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Criminality,Detainer Facility,Detainer Facility Code,...,Resume Custody Yes No,Detainer Lift Reason,Detainer Lift Reason Code,Active Investigation Yes No,Arrest Warrant Served Date,Detainer Type,Notify Release Request Yes No,TOD Current Duty Site,EID DTA ID,Anonymized Identifier
28,2024-07-08 00:00:00,ARKANSAS,New Orleans Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-04-01,8-Excluded/Removed - Inadmissibility,3 Other Immigration Violator,PULASKI COUNTY REG.DET.FAC.,PULASAR,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",00103f3e74679b755da13514ecf999d52ef39c4e
35,2024-01-28 00:00:00,VIRGINIA,Washington Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",GUATEMALA,2025-02-26,6-Deported/Removed - Deportability,1 Convicted Criminal,PRINCE WILLIAM,PWILLVA,...,NO,Detainer Declined by LEA,A,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,ERO - Pacific Enforcement Response Center,"b(6), b(7)c",0015da563be4d6695f33804021144210bade49dd
40,2024-03-27 00:00:00,TEXAS,Dallas Area of Responsibility,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",EL SALVADOR,2025-10-07,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,IRVING POLICE DEPT.,IRVNGTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",00197c0df52a1bb3936347d6dc9816c997a2fb38
46,2024-06-10 00:00:00,ARIZONA,Phoenix Area of Responsibility,"NOGALES, AZ, POE",MEXICO,2025-01-08,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,MARICOPA COUNTY JAIL,MCFAJAZ,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE","b(6), b(7)c",001d1303978e35d722d597f0e15f5692dd5286df
47,2024-08-12 00:00:00,ARIZONA,Phoenix Area of Responsibility,"NOGALES, AZ, POE",MEXICO,2025-01-08,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,US MARSHAL - PHOENIX,USMPHO,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Immigration Det...,NaN,"PHOENIX, AZ, DOCKET CONTROL OFFICE","b(6), b(7)c",001d1303978e35d722d597f0e15f5692dd5286df
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96824,2025-11-02 00:00:00,TEXAS,Dallas Area of Responsibility,"DALLAS, TX, POE",HONDURAS,2025-12-17,3-Voluntary Departure Confirmed,2 Pending Criminal Charges,GRAND PRAIRIE CITY JAIL,GRPRATX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"DALLAS, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",fff6a919573b3801f4824bfed092235e32c4f9d7
96834,2025-12-01 00:00:00,CALIFORNIA,Los Angeles Area of Responsibility,"SAN YSIDRO, CA, POE",MEXICO,2025-12-23,8-Excluded/Removed - Inadmissibility,1 Convicted Criminal,LOS ANGELES MET.DET.CTR.,BOPLOS,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"LOS ANGELES, CA, DOCKET CONTROL OFFICE","b(6), b(7)c",fffb1d13fc1ac1fffd53bfcf81c6d66305e4863b
98216,2025-10-15 00:00:00,TEXAS,NaN,"ALEXANDRIA INTERNATIONAL AIRPORT, POE",COLOMBIA,2025-11-28,3-Voluntary Departure Confirmed,2 Pending Criminal Charges,HARRIS COUNTY JAIL,HARISTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Montgomery County, TX Sub Office","b(6), b(7)c",NaN
101881,2025-11-22 00:00:00,TEXAS,Harlingen Area of Responsibility,"LAREDO, TX, POE",MEXICO,2025-11-25,9-VR Witnessed,2 Pending Criminal Charges,WEBB COUNTY JAIL,WEBCOTX,...,NO,Case Closed,C,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE","b(6), b(7)c",NaN
103624,2025-12-12 00:00:00,TEXAS,Harlingen Area of Responsibility,"LAREDO, TX, POE",MEXICO,2025-12-15,9-VR Witnessed,2 Pending Criminal Charges,WEBB COUNTY JAIL,WEBCOTX,...,NO,Booked into Detention,B,NaN,NaN,I247A - Immigration Detainer - Notice of Actio...,NaN,"ERO - Laredo, TX Detention Center","b(6), b(7)c",NaN

In [67]:
df_All2025.to_csv('FilteredData/All2025ICEDetainersData.csv', index=False)